from __future__ import annotations

import asyncio
import hashlib
import json
from collections import deque
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from tripchord.agents.companion_control_tools import (
    COMPANION_BUILD_FILE_ALLOWLIST,
    COMPANION_RELEASE_SEAL_RELATIVE_PATH,
    RELOAD_VERIFIED_COMPANION_TOOL,
    BrowserCompanionBuildReconcileResponse,
    BrowserCompanionBuildReconcileTimings,
    BrowserCompanionRuntimeExecutorAgent,
    BrowserCompanionRuntimeSupervisor,
    CompanionControlIdempotencyConflictError,
    CompanionControlToolError,
    CompanionControlTools,
    candidate_companion_build_identity,
    companion_build_sha256,
    companion_release_seal_bytes,
    default_companion_directory,
    verified_companion_build_identity,
)
from tripchord.agents.models import AgentRole, ToolPermission
from tripchord.agents.tools import ToolCall, ToolRegistry
from tripchord.providers.browser_bridge import (
    COMPANION_CONTROL_PROTOCOL_VERSION,
    BrowserCompanionBuildIdentity,
    BrowserCompanionControlKind,
    BrowserCompanionControlState,
    BrowserCompanionHeartbeat,
    BrowserCompanionReloadReasonCode,
    BrowserCompanionReloadRequestBody,
    BrowserCompanionReloadRequestSnapshot,
    BrowserCompanionStatusResponse,
    BrowserProvider,
)

NOW = datetime(2026, 8, 4, 8, 0, tzinfo=UTC)
OLD_BUILD_SHA256 = "a" * 64
OLD_RUNTIME_INSTANCE_ID = "runtime-old-0001"
NEW_RUNTIME_INSTANCE_ID = "runtime-new-0001"
COMPANION_ID = "chrome-mv3-fixture-extension"


def _canonical_build_sha256(root: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in COMPANION_BUILD_FILE_ALLOWLIST:
        payload = (root / relative_path).read_bytes()
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(str(len(payload)).encode("ascii"))
        digest.update(b"\0")
        digest.update(payload)
        digest.update(b"\0")
    return digest.hexdigest()


def _write_companion_build(root: Path) -> BrowserCompanionBuildIdentity:
    for relative_path in COMPANION_BUILD_FILE_ALLOWLIST:
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        if relative_path == "manifest.json":
            path.write_text(
                json.dumps({"manifest_version": 3, "version": "0.1.1"}),
                encoding="utf-8",
            )
        elif relative_path == "src/background.js":
            path.write_text(
                'const CONTENT_RUNTIME_VERSION = "2026-08-04.1";\n',
                encoding="utf-8",
            )
        else:
            path.write_bytes(f"fixture:{relative_path}\n".encode())
    identity = BrowserCompanionBuildIdentity(
        manifest_version="0.1.1",
        build_sha256=_canonical_build_sha256(root),
        content_runtime_version="2026-08-04.1",
    )
    meta = root / "src" / "build-meta.js"
    payload = json.dumps(identity.model_dump(mode="json"), ensure_ascii=False, indent=2)
    meta.write_text(
        "// Generated by scripts/update-build-meta.mjs. Do not edit by hand.\n"
        "globalThis.TRIPCHORD_COMPANION_BUILD_META = "
        f"Object.freeze({payload});\n",
        encoding="utf-8",
    )
    seal_path = root / COMPANION_RELEASE_SEAL_RELATIVE_PATH
    seal_path.write_bytes(companion_release_seal_bytes(root))
    seal_path.chmod(0o600)
    return identity


def _status(
    *,
    build_sha256: str = OLD_BUILD_SHA256,
    runtime_instance_id: str = OLD_RUNTIME_INSTANCE_ID,
    is_fresh: bool = True,
    companion_id: str = COMPANION_ID,
    protocol_version: str = COMPANION_CONTROL_PROTOCOL_VERSION,
) -> BrowserCompanionStatusResponse:
    build = BrowserCompanionBuildIdentity(
        protocol_version=protocol_version,
        manifest_version="0.1.0",
        build_sha256=build_sha256,
        content_runtime_version="2026-08-03.1",
    )
    return BrowserCompanionStatusResponse(
        status="connected" if is_fresh else "disconnected",
        server_time=NOW,
        stale_after_seconds=45,
        companions=(
            BrowserCompanionHeartbeat(
                companion_id=companion_id,
                providers=(
                    BrowserProvider.CTRIP,
                    BrowserProvider.QUNAR,
                    BrowserProvider.TONGCHENG,
                ),
                last_seen=NOW,
                age_seconds=0 if is_fresh else 46,
                is_fresh=is_fresh,
                build_identity=build,
                runtime_instance_id=runtime_instance_id,
            ),
        ),
    )


def _snapshot(
    target_sha256: str,
    state: BrowserCompanionControlState,
    *,
    companion_id: str = COMPANION_ID,
    observed_build_sha256: str | None = None,
    observed_runtime_instance_id: str | None = None,
    failure_code: str | None = None,
) -> BrowserCompanionReloadRequestSnapshot:
    applied_at = (
        NOW + timedelta(seconds=1) if state == BrowserCompanionControlState.APPLIED else None
    )
    return BrowserCompanionReloadRequestSnapshot(
        id="companion-reload-fixture-request",
        kind=BrowserCompanionControlKind.RELOAD_EXTENSION,
        companion_id=companion_id,
        idempotency_key="agent-reload-" + "1" * 64,
        expected_current_build_sha256=OLD_BUILD_SHA256,
        target_build_sha256=target_sha256,
        reason_code=BrowserCompanionReloadReasonCode.COMPANION_BUILD_CHANGED,
        state=state,
        requested_at=NOW,
        updated_at=applied_at or NOW,
        expires_at=NOW + timedelta(seconds=120),
        drain_deadline_at=NOW + timedelta(seconds=120),
        delivery_generation=1 if state != BrowserCompanionControlState.QUEUED else 0,
        expected_runtime_instance_id=OLD_RUNTIME_INSTANCE_ID,
        accepted_at=NOW if state == BrowserCompanionControlState.APPLIED else None,
        applied_at=applied_at,
        observed_build_sha256=observed_build_sha256,
        observed_runtime_instance_id=observed_runtime_instance_id,
        failure_code=failure_code,
    )


class _FakeBridge:
    def __init__(
        self,
        status: BrowserCompanionStatusResponse,
        initial: BrowserCompanionReloadRequestSnapshot | None = None,
        polls: tuple[BrowserCompanionReloadRequestSnapshot, ...] = (),
    ) -> None:
        self.status = status
        self.initial = initial
        self.polls = deque(polls)
        self.requests: list[tuple[str, str, BrowserCompanionReloadRequestBody]] = []
        self.status_calls = 0

    async def companion_status(self) -> BrowserCompanionStatusResponse:
        self.status_calls += 1
        return self.status

    async def request_reload(
        self,
        companion_id: str,
        *,
        idempotency_key: str,
        request: BrowserCompanionReloadRequestBody,
    ) -> BrowserCompanionReloadRequestSnapshot:
        self.requests.append((companion_id, idempotency_key, request))
        if self.initial is None:
            raise AssertionError("unexpected reload request")
        return self.initial

    async def get_reload_request(
        self,
        companion_id: str,
        request_id: str,
    ) -> BrowserCompanionReloadRequestSnapshot:
        assert companion_id == COMPANION_ID
        assert request_id == "companion-reload-fixture-request"
        if not self.polls:
            assert self.initial is not None
            return self.initial
        return self.polls.popleft()


def _call(**arguments: object) -> ToolCall:
    return ToolCall(
        id="reload-call-1",
        tool_name=RELOAD_VERIFIED_COMPANION_TOOL,
        task_id="runtime-maintenance-1",
        agent_role=AgentRole.EXECUTOR,
        arguments=arguments,
    )


def _reconcile_response(target_sha256: str) -> BrowserCompanionBuildReconcileResponse:
    return BrowserCompanionBuildReconcileResponse(
        request_id="companion-reload-fixture-request",
        companion_id=COMPANION_ID,
        state="applied",
        old_build_sha256=OLD_BUILD_SHA256,
        target_build_sha256=target_sha256,
        old_runtime_instance_id=OLD_RUNTIME_INSTANCE_ID,
        new_runtime_instance_id=NEW_RUNTIME_INSTANCE_ID,
        timings=BrowserCompanionBuildReconcileTimings(
            requested_at=NOW,
            updated_at=NOW + timedelta(seconds=1),
            accepted_at=NOW,
            applied_at=NOW + timedelta(seconds=1),
            elapsed_ms=1_000,
        ),
    )


class _FakeReconciler:
    def __init__(
        self,
        response: BrowserCompanionBuildReconcileResponse,
        *,
        failure: Exception | None = None,
    ) -> None:
        self.response = response
        self.failure = failure
        self.calls: list[tuple[BrowserCompanionReloadReasonCode, str]] = []

    async def reconcile_build(
        self,
        reason_code: BrowserCompanionReloadReasonCode,
        *,
        idempotency_key: str,
    ) -> BrowserCompanionBuildReconcileResponse:
        self.calls.append((reason_code, idempotency_key))
        if self.failure is not None:
            raise self.failure
        return self.response


def test_real_generated_build_metadata_parses_and_matches_fixed_manifest() -> None:
    root = default_companion_directory()
    identity = candidate_companion_build_identity(root)
    assert identity.protocol_version == COMPANION_CONTROL_PROTOCOL_VERSION
    assert identity.build_sha256 == companion_build_sha256(root)


def test_build_metadata_uses_json_schema_and_rejects_tamper_or_extra_fields(
    tmp_path: Path,
) -> None:
    identity = _write_companion_build(tmp_path)
    assert verified_companion_build_identity(tmp_path) == identity

    (tmp_path / "popup.css").write_text("tampered", encoding="utf-8")
    with pytest.raises(CompanionControlToolError, match="hash does not match"):
        verified_companion_build_identity(tmp_path)

    identity = _write_companion_build(tmp_path)
    meta = tmp_path / "src" / "build-meta.js"
    source = meta.read_text(encoding="utf-8")
    meta.write_text(source.replace("\n}", ',\n  "unexpected": true\n}'), encoding="utf-8")
    with pytest.raises(CompanionControlToolError, match="payload does not match"):
        verified_companion_build_identity(tmp_path)
    assert identity.build_sha256 == _canonical_build_sha256(tmp_path)


def test_verified_identity_requires_exact_canonical_release_seal(tmp_path: Path) -> None:
    identity = _write_companion_build(tmp_path)
    seal_path = tmp_path / COMPANION_RELEASE_SEAL_RELATIVE_PATH
    original_seal = seal_path.read_bytes()

    seal_path.unlink()
    with pytest.raises(CompanionControlToolError, match="release seal"):
        verified_companion_build_identity(tmp_path)

    seal_path.write_bytes(original_seal.replace(identity.build_sha256.encode(), b"f" * 64))
    seal_path.chmod(0o600)
    with pytest.raises(CompanionControlToolError, match="release seal"):
        verified_companion_build_identity(tmp_path)

    seal_path.write_bytes(original_seal.rstrip() + b" \n")
    seal_path.chmod(0o600)
    with pytest.raises(CompanionControlToolError, match="exact manifest/runtime/build"):
        verified_companion_build_identity(tmp_path)

    seal_path.write_bytes(original_seal)
    seal_path.chmod(0o644)
    with pytest.raises(CompanionControlToolError, match="exact mode 0600"):
        verified_companion_build_identity(tmp_path)


def test_verified_identity_rejects_stale_seal_for_new_valid_metadata(tmp_path: Path) -> None:
    old_identity = _write_companion_build(tmp_path)
    stale_seal = (tmp_path / COMPANION_RELEASE_SEAL_RELATIVE_PATH).read_bytes()
    (tmp_path / "popup.css").write_text("new audited candidate", encoding="utf-8")
    new_sha256 = _canonical_build_sha256(tmp_path)
    meta_path = tmp_path / "src" / "build-meta.js"
    meta_path.write_text(
        meta_path.read_text(encoding="utf-8").replace(
            old_identity.build_sha256,
            new_sha256,
        ),
        encoding="utf-8",
    )
    assert candidate_companion_build_identity(tmp_path).build_sha256 == new_sha256
    (tmp_path / COMPANION_RELEASE_SEAL_RELATIVE_PATH).write_bytes(stale_seal)
    (tmp_path / COMPANION_RELEASE_SEAL_RELATIVE_PATH).chmod(0o600)

    with pytest.raises(CompanionControlToolError, match="exact manifest/runtime/build"):
        verified_companion_build_identity(tmp_path)


def test_tool_schema_exposes_only_reason_enum(tmp_path: Path) -> None:
    _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status())
    registry = ToolRegistry()
    CompanionControlTools(bridge, companion_directory=tmp_path).register(registry)

    spec = registry.spec(RELOAD_VERIFIED_COMPANION_TOOL)
    assert spec.permission == ToolPermission.REVERSIBLE_WRITE
    assert spec.allowed_roles == (AgentRole.EXECUTOR,)
    assert spec.input_schema == {
        "type": "object",
        "properties": {
            "reason_code": {
                "type": "string",
                "enum": [reason.value for reason in BrowserCompanionReloadReasonCode],
            }
        },
        "required": ["reason_code"],
        "additionalProperties": False,
    }
    serialized = json.dumps(spec.input_schema)
    for forbidden in ("build_sha256", "url", "script", "token", "path"):
        assert forbidden not in serialized.lower()


@pytest.mark.asyncio
async def test_tool_rejects_smuggled_control_arguments_before_any_bridge_call(
    tmp_path: Path,
) -> None:
    bridge = _FakeBridge(_status())
    registry = ToolRegistry()
    CompanionControlTools(bridge, companion_directory=tmp_path).register(registry)

    with pytest.raises(CompanionControlToolError, match="accepts only"):
        await registry.invoke(
            _call(
                reason_code="companion_build_changed",
                target_build_sha256="f" * 64,
            )
        )
    assert bridge.requests == []


@pytest.mark.asyncio
async def test_tool_verifies_build_requests_reload_and_returns_sanitized_receipt(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    queued = _snapshot(target.build_sha256, BrowserCompanionControlState.QUEUED)
    applied = _snapshot(
        target.build_sha256,
        BrowserCompanionControlState.APPLIED,
        observed_build_sha256=target.build_sha256,
        observed_runtime_instance_id=NEW_RUNTIME_INSTANCE_ID,
    )
    bridge = _FakeBridge(_status(), queued, (applied,))

    async def no_wait(_: float) -> None:
        return None

    registry = ToolRegistry()
    CompanionControlTools(
        bridge,
        companion_directory=tmp_path,
        poll_interval_seconds=0.001,
        wait_timeout_seconds=15,
        now=lambda: NOW,
        sleep=no_wait,
    ).register(registry)
    receipt = await registry.invoke(_call(reason_code="companion_build_changed"))

    assert len(bridge.requests) == 1
    companion_id, idempotency_key, request = bridge.requests[0]
    assert companion_id == COMPANION_ID
    assert idempotency_key.startswith("agent-reload-")
    assert request.expected_current_build_sha256 == OLD_BUILD_SHA256
    assert request.target_build_sha256 == target.build_sha256
    assert request.reason_code == BrowserCompanionReloadReasonCode.COMPANION_BUILD_CHANGED
    assert receipt.output == {
        "request_id": "companion-reload-fixture-request",
        "companion_id": COMPANION_ID,
        "state": "applied",
        "old_build_sha256": OLD_BUILD_SHA256,
        "target_build_sha256": target.build_sha256,
        "old_runtime_instance_id": OLD_RUNTIME_INSTANCE_ID,
        "new_runtime_instance_id": NEW_RUNTIME_INSTANCE_ID,
        "timings": {
            "requested_at": NOW.isoformat(),
            "updated_at": (NOW + timedelta(seconds=1)).isoformat(),
            "accepted_at": NOW.isoformat(),
            "applied_at": (NOW + timedelta(seconds=1)).isoformat(),
            "elapsed_ms": 1000,
        },
    }
    assert not any(
        forbidden in json.dumps(receipt.output).lower()
        for forbidden in ("bridge_token", "control_token", "http://", "https://", "script_path")
    )


@pytest.mark.asyncio
async def test_already_current_is_honest_noop_without_reload_request(tmp_path: Path) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status(build_sha256=target.build_sha256))
    registry = ToolRegistry()
    CompanionControlTools(
        bridge,
        companion_directory=tmp_path,
        now=lambda: NOW,
    ).register(registry)

    receipt = await registry.invoke(_call(reason_code="recovery"))
    assert receipt.output["state"] == "already_current"
    assert receipt.output["request_id"] is None
    assert bridge.requests == []


@pytest.mark.asyncio
async def test_tool_requires_exactly_one_fresh_control_v1_chrome_companion(
    tmp_path: Path,
) -> None:
    _write_companion_build(tmp_path)
    stale = _status(is_fresh=False)
    bridge = _FakeBridge(stale)
    registry = ToolRegistry()
    CompanionControlTools(bridge, companion_directory=tmp_path).register(registry)
    with pytest.raises(CompanionControlToolError, match="exactly one fresh"):
        await registry.invoke(_call(reason_code="recovery"))

    first = _status().companions[0]
    second = _status(companion_id="chrome-mv3-second-extension").companions[0]
    bridge.status = BrowserCompanionStatusResponse(
        status="connected",
        server_time=NOW,
        stale_after_seconds=45,
        companions=(first, second),
    )
    with pytest.raises(CompanionControlToolError, match="exactly one fresh"):
        await registry.invoke(_call(reason_code="recovery"))


@pytest.mark.asyncio
async def test_failed_or_unproven_reload_never_returns_success(tmp_path: Path) -> None:
    target = _write_companion_build(tmp_path)
    failed_bridge = _FakeBridge(
        _status(),
        _snapshot(
            target.build_sha256,
            BrowserCompanionControlState.FAILED,
            failure_code="reload_timeout",
        ),
    )
    registry = ToolRegistry()
    CompanionControlTools(failed_bridge, companion_directory=tmp_path).register(registry)
    with pytest.raises(CompanionControlToolError, match="reload_timeout"):
        await registry.invoke(_call(reason_code="recovery"))

    unproven_bridge = _FakeBridge(
        _status(),
        _snapshot(
            target.build_sha256,
            BrowserCompanionControlState.APPLIED,
            observed_build_sha256=target.build_sha256,
            observed_runtime_instance_id=OLD_RUNTIME_INSTANCE_ID,
        ),
    )
    registry = ToolRegistry()
    CompanionControlTools(unproven_bridge, companion_directory=tmp_path).register(registry)
    with pytest.raises(CompanionControlToolError, match="new companion runtime"):
        await registry.invoke(_call(reason_code="recovery"))


@pytest.mark.asyncio
async def test_reload_wait_timeout_is_bounded_and_explicit(tmp_path: Path) -> None:
    target = _write_companion_build(tmp_path)
    queued = _snapshot(target.build_sha256, BrowserCompanionControlState.QUEUED)
    bridge = _FakeBridge(_status(), queued)
    monotonic_values = iter((0.0, 16.0))
    registry = ToolRegistry()
    CompanionControlTools(
        bridge,
        companion_directory=tmp_path,
        wait_timeout_seconds=15,
        monotonic=lambda: next(monotonic_values),
    ).register(registry)
    with pytest.raises(CompanionControlToolError, match="timed out"):
        await registry.invoke(_call(reason_code="operator_requested"))


@pytest.mark.asyncio
async def test_runtime_executor_constructs_one_executor_tool_call_per_idempotency_key(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status(build_sha256=target.build_sha256))
    runtime_agent = BrowserCompanionRuntimeExecutorAgent(
        bridge,
        companion_directory=tmp_path,
    )

    first = await runtime_agent.reconcile_build(
        BrowserCompanionReloadReasonCode.RECOVERY,
        idempotency_key="runtime-reconcile-0001",
    )
    second = await runtime_agent.reconcile_build(
        BrowserCompanionReloadReasonCode.RECOVERY,
        idempotency_key="runtime-reconcile-0001",
    )

    assert first == second
    assert first.state == "already_current"
    assert bridge.status_calls == 1
    assert runtime_agent.registry.spec(RELOAD_VERIFIED_COMPANION_TOOL).allowed_roles == (
        AgentRole.EXECUTOR,
    )
    with pytest.raises(CompanionControlIdempotencyConflictError):
        await runtime_agent.reconcile_build(
            BrowserCompanionReloadReasonCode.OPERATOR_REQUESTED,
            idempotency_key="runtime-reconcile-0001",
        )


@pytest.mark.asyncio
async def test_runtime_supervisor_is_noop_when_verified_build_is_current(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status(build_sha256=target.build_sha256))
    reconciler = _FakeReconciler(_reconcile_response(target.build_sha256))
    supervisor = BrowserCompanionRuntimeSupervisor(
        bridge,
        reconciler,
        companion_directory=tmp_path,
    )

    assert await supervisor.run_once() == "already_current"
    assert supervisor.attempt_count == 0
    assert reconciler.calls == []


@pytest.mark.asyncio
async def test_runtime_supervisor_never_reloads_an_unsealed_candidate(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    (tmp_path / COMPANION_RELEASE_SEAL_RELATIVE_PATH).unlink()
    bridge = _FakeBridge(_status())
    reconciler = _FakeReconciler(_reconcile_response(target.build_sha256))
    supervisor = BrowserCompanionRuntimeSupervisor(
        bridge,
        reconciler,
        companion_directory=tmp_path,
    )

    assert await supervisor.run_once() == "local_build_invalid"
    assert supervisor.last_failure_code == "local_build_validation_failed"
    assert supervisor.attempt_count == 0
    assert bridge.status_calls == 0
    assert reconciler.calls == []


@pytest.mark.asyncio
async def test_runtime_supervisor_triggers_bounded_agent_for_changed_build(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status())
    reconciler = _FakeReconciler(_reconcile_response(target.build_sha256))
    supervisor = BrowserCompanionRuntimeSupervisor(
        bridge,
        reconciler,
        companion_directory=tmp_path,
    )

    assert await supervisor.run_once() == "applied"
    assert supervisor.attempt_count == 1
    assert supervisor.last_reconcile_result is not None
    assert supervisor.last_reconcile_result.state == "applied"
    assert supervisor.last_reconcile_result.target_build_sha256 == target.build_sha256
    assert reconciler.calls == [
        (
            BrowserCompanionReloadReasonCode.COMPANION_BUILD_CHANGED,
            f"supervisor-{target.build_sha256}-1",
        )
    ]


@pytest.mark.asyncio
async def test_runtime_supervisor_retries_one_target_with_cooldown_and_finite_budget(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status())
    reconciler = _FakeReconciler(
        _reconcile_response(target.build_sha256),
        failure=RuntimeError("fixture failure for bounded recovery"),
    )
    clock = [0.0]
    supervisor = BrowserCompanionRuntimeSupervisor(
        bridge,
        reconciler,
        companion_directory=tmp_path,
        retry_cooldown_seconds=30,
        max_attempts_per_target=3,
        monotonic=lambda: clock[0],
    )

    assert await supervisor.run_once() == "reload_failed"
    assert await supervisor.run_once() == "failed_target_cooldown"
    clock[0] = 30
    assert await supervisor.run_once() == "reload_failed"
    assert await supervisor.run_once() == "failed_target_cooldown"
    clock[0] = 60
    assert await supervisor.run_once() == "reload_failed"
    assert await supervisor.run_once() == "failed_target_exhausted"
    assert supervisor.attempt_count == 3
    assert supervisor.failed_target_sha256 == target.build_sha256
    assert reconciler.calls == [
        (
            BrowserCompanionReloadReasonCode.COMPANION_BUILD_CHANGED,
            f"supervisor-{target.build_sha256}-{generation}",
        )
        for generation in (1, 2, 3)
    ]
    assert bridge.status_calls == 6


@pytest.mark.asyncio
async def test_runtime_supervisor_waits_for_legacy_worker_identity_without_failure(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    legacy = _status().companions[0].model_copy(
        update={"build_identity": None, "runtime_instance_id": None}
    )
    bridge = _FakeBridge(
        BrowserCompanionStatusResponse(
            status="connected",
            server_time=NOW,
            stale_after_seconds=45,
            companions=(legacy,),
        )
    )
    reconciler = _FakeReconciler(_reconcile_response(target.build_sha256))
    supervisor = BrowserCompanionRuntimeSupervisor(
        bridge,
        reconciler,
        companion_directory=tmp_path,
    )

    assert await supervisor.run_once() == "waiting_for_control_capable_companion"
    assert supervisor.failed_target_sha256 is None
    assert supervisor.attempt_count == 0
    assert reconciler.calls == []


@pytest.mark.asyncio
async def test_runtime_executor_evicts_only_completed_idempotency_records(
    tmp_path: Path,
) -> None:
    target = _write_companion_build(tmp_path)
    bridge = _FakeBridge(_status(build_sha256=target.build_sha256))
    runtime_agent = BrowserCompanionRuntimeExecutorAgent(
        bridge,
        companion_directory=tmp_path,
        max_idempotency_records=1,
    )

    await runtime_agent.reconcile_build(
        BrowserCompanionReloadReasonCode.RECOVERY,
        idempotency_key="runtime-capacity-complete-0001",
    )
    await runtime_agent.reconcile_build(
        BrowserCompanionReloadReasonCode.RECOVERY,
        idempotency_key="runtime-capacity-complete-0002",
    )
    assert bridge.status_calls == 2

    started = asyncio.Event()
    release = asyncio.Event()

    class _BlockingBridge(_FakeBridge):
        async def companion_status(self) -> BrowserCompanionStatusResponse:
            started.set()
            await release.wait()
            return self.status

    blocking_bridge = _BlockingBridge(_status(build_sha256=target.build_sha256))
    bounded_agent = BrowserCompanionRuntimeExecutorAgent(
        blocking_bridge,
        companion_directory=tmp_path,
        max_idempotency_records=1,
    )
    pending = asyncio.create_task(
        bounded_agent.reconcile_build(
            BrowserCompanionReloadReasonCode.RECOVERY,
            idempotency_key="runtime-capacity-pending-0001",
        )
    )
    await started.wait()
    with pytest.raises(CompanionControlToolError, match="capacity exceeded"):
        await bounded_agent.reconcile_build(
            BrowserCompanionReloadReasonCode.RECOVERY,
            idempotency_key="runtime-capacity-pending-0002",
        )
    release.set()
    await pending
