from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import os
import re
import stat
import time
from collections import OrderedDict
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal, Protocol

from pydantic import Field, JsonValue, TypeAdapter, ValidationError

from tripchord.agents.models import AgentRole, ToolPermission
from tripchord.agents.tools import ToolCall, ToolRegistry, ToolSpec
from tripchord.domain.common import DomainModel
from tripchord.providers.browser_bridge import (
    COMPANION_CONTROL_PROTOCOL_VERSION,
    BrowserCompanionBuildIdentity,
    BrowserCompanionControlState,
    BrowserCompanionHeartbeat,
    BrowserCompanionReloadReasonCode,
    BrowserCompanionReloadRequestBody,
    BrowserCompanionReloadRequestSnapshot,
    BrowserCompanionStatusResponse,
)

RELOAD_VERIFIED_COMPANION_TOOL = "reload_verified_browser_companion"
_MAX_RUNTIME_IDEMPOTENCY_RECORDS = 256
_SAFE_IDEMPOTENCY_KEY = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._:-]{7,127}\Z")
_DEFAULT_SUPERVISOR_MAX_ATTEMPTS_PER_TARGET = 3
_DEFAULT_SUPERVISOR_RETRY_COOLDOWN_SECONDS = 30.0
COMPANION_RELEASE_SEAL_RELATIVE_PATH = ".tripchord-release-seal.json"

# This is a release manifest, not a caller-controlled file list. Keep it byte-for-byte
# aligned with the extension build-identity generator.
COMPANION_BUILD_FILE_ALLOWLIST: tuple[str, ...] = (
    "manifest.json",
    "popup.html",
    "popup.css",
    "popup.js",
    "offscreen.html",
    "src/background.js",
    "src/content.js",
    "src/offscreen.js",
    "src/parser.js",
)

_BUILD_META_RELATIVE_PATH = "src/build-meta.js"
_MAX_BUILD_FILE_BYTES = 16 * 1024 * 1024
_MAX_RELEASE_SEAL_BYTES = 16 * 1024
_BUILD_META_PATTERN = re.compile(
    r"\A// Generated by scripts/update-build-meta\.mjs\. Do not edit by hand\.\r?\n"
    r"globalThis\.TRIPCHORD_COMPANION_BUILD_META\s*=\s*"
    r"Object\.freeze\((?P<payload>\{[\s\S]*\})\);\s*\Z"
)
_CONTENT_RUNTIME_VERSION_PATTERN = re.compile(
    r'const CONTENT_RUNTIME_VERSION = "([A-Za-z0-9][A-Za-z0-9._+-]*)";'
)


class CompanionControlToolError(RuntimeError):
    """A fail-closed local companion control error safe to surface to the Agent."""


class CompanionControlInvalidIdempotencyKeyError(CompanionControlToolError):
    """Raised before invocation when the caller's idempotency key is malformed."""


class CompanionControlIdempotencyConflictError(CompanionControlToolError):
    """Raised when one idempotency key is reused for a different bounded action."""


class BrowserCompanionBuildReconcileRequest(DomainModel):
    """The complete model/caller-controlled surface for the runtime Agent."""

    reason_code: BrowserCompanionReloadReasonCode


class BrowserCompanionBuildReconcileTimings(DomainModel):
    requested_at: datetime
    updated_at: datetime
    accepted_at: datetime | None = None
    applied_at: datetime | None = None
    elapsed_ms: int = Field(ge=0)


class BrowserCompanionBuildReconcileResponse(DomainModel):
    """Strict, token-free projection of the underlying ToolReceipt output."""

    request_id: str | None = Field(
        default=None,
        pattern=r"^companion-reload-[A-Za-z0-9_-]+$",
    )
    companion_id: str = Field(min_length=1, max_length=128)
    state: Literal["already_current", "applied"]
    old_build_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    target_build_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    old_runtime_instance_id: str = Field(
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$"
    )
    new_runtime_instance_id: str = Field(
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$"
    )
    timings: BrowserCompanionBuildReconcileTimings


class BrowserCompanionReleaseSeal(DomainModel):
    """Deterministic local receipt written only after the release contracts pass."""

    schema_version: Literal["tripchord-companion-release-seal-v1"] = (
        "tripchord-companion-release-seal-v1"
    )
    protocol_version: Literal["tripchord-companion-control-v1"]
    manifest_version: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._+-]*$",
    )
    build_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    content_runtime_version: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._+-]*$",
    )
    build_meta_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")


@dataclass(frozen=True)
class _CompanionBuildCandidate:
    identity: BrowserCompanionBuildIdentity
    build_meta_sha256: str


class CompanionControlBridge(Protocol):
    async def companion_status(self) -> BrowserCompanionStatusResponse: ...

    async def request_reload(
        self,
        companion_id: str,
        *,
        idempotency_key: str,
        request: BrowserCompanionReloadRequestBody,
    ) -> BrowserCompanionReloadRequestSnapshot: ...

    async def get_reload_request(
        self,
        companion_id: str,
        request_id: str,
    ) -> BrowserCompanionReloadRequestSnapshot: ...


class CompanionRuntimeReconciler(Protocol):
    async def reconcile_build(
        self,
        reason_code: BrowserCompanionReloadReasonCode,
        *,
        idempotency_key: str,
    ) -> BrowserCompanionBuildReconcileResponse: ...


def default_companion_directory() -> Path:
    return Path(__file__).resolve().parents[5] / "apps" / "browser-companion"


def _fixed_regular_file(root: Path, relative_path: str) -> Path:
    candidate = root / relative_path
    if candidate.is_symlink() or not candidate.is_file():
        raise CompanionControlToolError(
            f"companion build input is missing or not a regular file: {relative_path}"
        )
    resolved_root = root.resolve()
    resolved = candidate.resolve()
    if not resolved.is_relative_to(resolved_root):
        raise CompanionControlToolError(
            f"companion build input escapes the fixed companion directory: {relative_path}"
        )
    if resolved.stat().st_size > _MAX_BUILD_FILE_BYTES:
        raise CompanionControlToolError(
            f"companion build input exceeds the audited size bound: {relative_path}"
        )
    return resolved


def companion_build_sha256(companion_directory: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in COMPANION_BUILD_FILE_ALLOWLIST:
        payload = _fixed_regular_file(companion_directory, relative_path).read_bytes()
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(str(len(payload)).encode("ascii"))
        digest.update(b"\0")
        digest.update(payload)
        digest.update(b"\0")
    return digest.hexdigest()


def _candidate_companion_build(
    companion_directory: Path,
) -> _CompanionBuildCandidate:
    """Validate metadata and source bytes without granting reload authority.

    This is intentionally separate from ``verified_companion_build_identity``:
    the release gate needs to test an unsealed candidate, while every runtime
    Agent and supervisor call must require the post-test release seal.
    """

    meta_path = _fixed_regular_file(companion_directory, _BUILD_META_RELATIVE_PATH)
    try:
        meta_bytes = meta_path.read_bytes()
        meta_source = meta_bytes.decode("utf-8")
    except UnicodeError as exc:
        raise CompanionControlToolError("companion build metadata is not valid UTF-8") from exc
    match = _BUILD_META_PATTERN.fullmatch(meta_source)
    if match is None:
        raise CompanionControlToolError("companion build metadata does not match the frozen schema")

    try:
        identity = BrowserCompanionBuildIdentity.model_validate_json(match.group("payload"))
    except ValidationError as exc:
        raise CompanionControlToolError(
            "companion build metadata payload does not match the frozen schema"
        ) from exc

    expected_sha256 = companion_build_sha256(companion_directory)
    if not hmac.compare_digest(identity.build_sha256, expected_sha256):
        raise CompanionControlToolError(
            "companion build metadata hash does not match the fixed release manifest"
        )

    try:
        manifest: object = json.loads(
            _fixed_regular_file(companion_directory, "manifest.json").read_text(
                encoding="utf-8"
            )
        )
        background = _fixed_regular_file(
            companion_directory,
            "src/background.js",
        ).read_text(encoding="utf-8")
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise CompanionControlToolError(
            "companion manifest or background runtime is not valid UTF-8"
        ) from exc
    if not isinstance(manifest, dict) or manifest.get("version") != identity.manifest_version:
        raise CompanionControlToolError(
            "companion build metadata manifest version does not match manifest.json"
        )
    runtime_match = _CONTENT_RUNTIME_VERSION_PATTERN.search(background)
    if runtime_match is None:
        raise CompanionControlToolError(
            "companion background.js has no auditable CONTENT_RUNTIME_VERSION"
        )
    if runtime_match.group(1) != identity.content_runtime_version:
        raise CompanionControlToolError(
            "companion build metadata runtime version does not match background.js"
        )

    # Detect a source or metadata replacement during the validation pass.  A
    # later mutation remains fail-closed because it invalidates the sealed hash
    # at the next supervisor/tool check.
    if meta_path.read_bytes() != meta_bytes or not hmac.compare_digest(
        companion_build_sha256(companion_directory),
        expected_sha256,
    ):
        raise CompanionControlToolError("companion build changed during local validation")
    return _CompanionBuildCandidate(
        identity=identity,
        build_meta_sha256=hashlib.sha256(meta_bytes).hexdigest(),
    )


def candidate_companion_build_identity(
    companion_directory: Path | None = None,
) -> BrowserCompanionBuildIdentity:
    """Return an unsealed candidate identity for the deterministic release gate only."""

    root = companion_directory or default_companion_directory()
    return _candidate_companion_build(root).identity


def _release_seal_for_candidate(
    candidate: _CompanionBuildCandidate,
) -> BrowserCompanionReleaseSeal:
    identity = candidate.identity
    return BrowserCompanionReleaseSeal(
        protocol_version=identity.protocol_version,
        manifest_version=identity.manifest_version,
        build_sha256=identity.build_sha256,
        content_runtime_version=identity.content_runtime_version,
        build_meta_sha256=candidate.build_meta_sha256,
    )


def _canonical_release_seal_bytes(seal: BrowserCompanionReleaseSeal) -> bytes:
    payload = json.dumps(
        seal.model_dump(mode="json"),
        ensure_ascii=True,
        indent=2,
        sort_keys=True,
    )
    return f"{payload}\n".encode()


def companion_release_seal_bytes(
    companion_directory: Path | None = None,
) -> bytes:
    """Build the canonical seal bytes for a stable, unsealed candidate tree."""

    root = companion_directory or default_companion_directory()
    return _canonical_release_seal_bytes(
        _release_seal_for_candidate(_candidate_companion_build(root))
    )


def verified_companion_build_identity(
    companion_directory: Path | None = None,
) -> BrowserCompanionBuildIdentity:
    root = companion_directory or default_companion_directory()
    candidate_before = _candidate_companion_build(root)
    try:
        seal_path = _fixed_regular_file(root, COMPANION_RELEASE_SEAL_RELATIVE_PATH)
    except CompanionControlToolError as exc:
        raise CompanionControlToolError(
            "companion release seal is missing or is not a safe regular file"
        ) from exc
    seal_stat = seal_path.stat()
    if seal_stat.st_size > _MAX_RELEASE_SEAL_BYTES:
        raise CompanionControlToolError("companion release seal exceeds the audited size bound")
    if seal_stat.st_uid != os.getuid() or stat.S_IMODE(seal_stat.st_mode) != 0o600:
        raise CompanionControlToolError(
            "companion release seal must be current-user-owned with exact mode 0600"
        )
    try:
        seal_bytes = seal_path.read_bytes()
        seal = BrowserCompanionReleaseSeal.model_validate_json(seal_bytes)
    except ValidationError as exc:
        raise CompanionControlToolError(
            "companion release seal payload does not match the frozen schema"
        ) from exc
    except UnicodeError as exc:
        raise CompanionControlToolError("companion release seal is not valid UTF-8 JSON") from exc

    candidate_after = _candidate_companion_build(root)
    if candidate_before != candidate_after:
        raise CompanionControlToolError("companion build changed while checking the release seal")
    expected_seal = _release_seal_for_candidate(candidate_after)
    if seal != expected_seal or not hmac.compare_digest(
        seal_bytes,
        _canonical_release_seal_bytes(expected_seal),
    ):
        raise CompanionControlToolError(
            "companion release seal does not match the exact manifest/runtime/build identity"
        )
    return candidate_after.identity


class CompanionControlTools:
    """Register a bounded runtime-control tool without exposing its control plane to the model."""

    def __init__(
        self,
        bridge: CompanionControlBridge,
        *,
        companion_directory: Path | None = None,
        poll_interval_seconds: float = 0.25,
        wait_timeout_seconds: float = 120,
        now: Callable[[], datetime] | None = None,
        monotonic: Callable[[], float] | None = None,
        sleep: Callable[[float], Awaitable[None]] | None = None,
    ) -> None:
        if poll_interval_seconds <= 0:
            raise ValueError("poll_interval_seconds must be positive")
        if wait_timeout_seconds <= 0 or wait_timeout_seconds > 600:
            raise ValueError("wait_timeout_seconds must be between 0 and 600")
        self._bridge = bridge
        self._companion_directory = companion_directory or default_companion_directory()
        self._poll_interval_seconds = poll_interval_seconds
        self._wait_timeout_seconds = wait_timeout_seconds
        self._now = now or (lambda: datetime.now(UTC))
        self._monotonic = monotonic or time.monotonic
        self._sleep = sleep or asyncio.sleep

    def register(self, registry: ToolRegistry) -> None:
        registry.register(
            ToolSpec(
                name=RELOAD_VERIFIED_COMPANION_TOOL,
                description=(
                    "在固定 TripChord 构建通过本地哈希验证后，排空活跃查询并重载已配对的 "
                    "Chrome Companion；不能指定文件、地址、构建哈希或令牌"
                ),
                permission=ToolPermission.REVERSIBLE_WRITE,
                allowed_roles=(AgentRole.EXECUTOR,),
                input_schema={
                    "type": "object",
                    "properties": {
                        "reason_code": {
                            "type": "string",
                            "enum": [reason.value for reason in BrowserCompanionReloadReasonCode],
                        }
                    },
                    "required": ["reason_code"],
                    "additionalProperties": False,
                },
            ),
            self._reload_verified_companion,
        )

    async def _reload_verified_companion(self, call: ToolCall) -> dict[str, JsonValue]:
        if set(call.arguments) != {"reason_code"}:
            raise CompanionControlToolError(
                "reload tool accepts only the reason_code enum; paths, URLs, hashes, "
                "and tokens are forbidden"
            )
        raw_reason = call.arguments.get("reason_code")
        if not isinstance(raw_reason, str):
            raise CompanionControlToolError("reason_code must be a string enum value")
        try:
            reason = BrowserCompanionReloadReasonCode(raw_reason)
        except ValueError as exc:
            raise CompanionControlToolError("reason_code is not an allowed reload reason") from exc

        target_identity = verified_companion_build_identity(self._companion_directory)
        companion = await self._unique_fresh_control_companion()
        old_identity = companion.build_identity
        old_runtime_instance_id = companion.runtime_instance_id
        if old_identity is None or old_runtime_instance_id is None:
            raise CompanionControlToolError("selected companion has no verified runtime identity")

        started_at = self._now()
        started_monotonic = self._monotonic()
        if hmac.compare_digest(old_identity.build_sha256, target_identity.build_sha256):
            return self._validated_output(
                {
                    "request_id": None,
                    "companion_id": companion.companion_id,
                    "state": "already_current",
                    "old_build_sha256": old_identity.build_sha256,
                    "target_build_sha256": target_identity.build_sha256,
                    "old_runtime_instance_id": old_runtime_instance_id,
                    "new_runtime_instance_id": old_runtime_instance_id,
                    "timings": {
                        "requested_at": started_at.isoformat(),
                        "updated_at": started_at.isoformat(),
                        "accepted_at": None,
                        "applied_at": None,
                        "elapsed_ms": 0,
                    },
                }
            )

        idempotency_key = self._idempotency_key(
            call,
            reason,
            old_identity.build_sha256,
            target_identity.build_sha256,
        )
        expires_in_seconds = max(15, min(600, int(self._wait_timeout_seconds)))
        request = BrowserCompanionReloadRequestBody(
            expected_current_build_sha256=old_identity.build_sha256,
            target_build_sha256=target_identity.build_sha256,
            reason_code=reason,
            expires_in_seconds=expires_in_seconds,
            max_drain_seconds=expires_in_seconds,
        )
        snapshot = await self._bridge.request_reload(
            companion.companion_id,
            idempotency_key=idempotency_key,
            request=request,
        )
        self._validate_snapshot_scope(
            snapshot,
            companion_id=companion.companion_id,
            old_build_sha256=old_identity.build_sha256,
            target_build_sha256=target_identity.build_sha256,
        )

        deadline = started_monotonic + self._wait_timeout_seconds
        while not snapshot.state.terminal:
            remaining = deadline - self._monotonic()
            if remaining <= 0:
                raise CompanionControlToolError(
                    "verified companion reload timed out before a terminal receipt"
                )
            await self._sleep(min(self._poll_interval_seconds, remaining))
            snapshot = await self._bridge.get_reload_request(
                companion.companion_id,
                snapshot.id,
            )
            self._validate_snapshot_scope(
                snapshot,
                companion_id=companion.companion_id,
                old_build_sha256=old_identity.build_sha256,
                target_build_sha256=target_identity.build_sha256,
            )

        if snapshot.state != BrowserCompanionControlState.APPLIED:
            failure_code = snapshot.failure_code or snapshot.state.value
            raise CompanionControlToolError(
                f"verified companion reload ended in {snapshot.state.value}: {failure_code}"
            )
        if snapshot.observed_build_sha256 != target_identity.build_sha256:
            raise CompanionControlToolError(
                "reload receipt did not prove the requested target build"
            )
        if snapshot.observed_runtime_instance_id is None or hmac.compare_digest(
            snapshot.observed_runtime_instance_id,
            old_runtime_instance_id,
        ):
            raise CompanionControlToolError(
                "reload receipt did not prove a new companion runtime instance"
            )
        if snapshot.applied_at is None:
            raise CompanionControlToolError("applied reload receipt has no applied_at timestamp")

        return self._validated_output(
            {
                "request_id": snapshot.id,
                "companion_id": companion.companion_id,
                "state": snapshot.state.value,
                "old_build_sha256": old_identity.build_sha256,
                "target_build_sha256": target_identity.build_sha256,
                "old_runtime_instance_id": old_runtime_instance_id,
                "new_runtime_instance_id": snapshot.observed_runtime_instance_id,
                "timings": {
                    "requested_at": snapshot.requested_at.isoformat(),
                    "updated_at": snapshot.updated_at.isoformat(),
                    "accepted_at": (
                        snapshot.accepted_at.isoformat()
                        if snapshot.accepted_at is not None
                        else None
                    ),
                    "applied_at": snapshot.applied_at.isoformat(),
                    "elapsed_ms": max(
                        0,
                        int((snapshot.applied_at - snapshot.requested_at).total_seconds() * 1000),
                    ),
                },
            }
        )

    async def _unique_fresh_control_companion(self) -> BrowserCompanionHeartbeat:
        status = await self._bridge.companion_status()
        candidates = tuple(
            companion
            for companion in status.companions
            if companion.is_fresh
            and companion.companion_id.startswith("chrome-mv3-")
            and companion.build_identity is not None
            and companion.build_identity.protocol_version == COMPANION_CONTROL_PROTOCOL_VERSION
            and companion.runtime_instance_id is not None
        )
        if len(candidates) != 1:
            raise CompanionControlToolError(
                "reload requires exactly one fresh control-v1 Chrome companion"
            )
        return candidates[0]

    @staticmethod
    def _idempotency_key(
        call: ToolCall,
        reason: BrowserCompanionReloadReasonCode,
        old_build_sha256: str,
        target_build_sha256: str,
    ) -> str:
        payload = "\0".join(
            (
                RELOAD_VERIFIED_COMPANION_TOOL,
                call.id,
                call.task_id,
                call.agent_role.value,
                reason.value,
                old_build_sha256,
                target_build_sha256,
            )
        )
        return f"agent-reload-{hashlib.sha256(payload.encode()).hexdigest()}"

    @staticmethod
    def _validate_snapshot_scope(
        snapshot: BrowserCompanionReloadRequestSnapshot,
        *,
        companion_id: str,
        old_build_sha256: str,
        target_build_sha256: str,
    ) -> None:
        if (
            snapshot.companion_id != companion_id
            or not hmac.compare_digest(
                snapshot.expected_current_build_sha256,
                old_build_sha256,
            )
            or not hmac.compare_digest(snapshot.target_build_sha256, target_build_sha256)
        ):
            raise CompanionControlToolError(
                "browser bridge returned a reload request outside the verified companion scope"
            )

    @staticmethod
    def _validated_output(value: dict[str, object]) -> dict[str, JsonValue]:
        return TypeAdapter(dict[str, JsonValue]).validate_python(value)


@dataclass(frozen=True, slots=True)
class _RuntimeAgentInvocation:
    reason_code: BrowserCompanionReloadReasonCode
    task: asyncio.Task[BrowserCompanionBuildReconcileResponse]


class BrowserCompanionRuntimeExecutorAgent:
    """Deterministic Executor Agent boundary for the bounded reload tool.

    The caller supplies only an audited reason enum and an HTTP/control-plane
    idempotency key.  Build paths, release files, hashes, URLs and credentials
    never enter the ToolCall argument surface.
    """

    def __init__(
        self,
        bridge: CompanionControlBridge,
        *,
        companion_directory: Path | None = None,
        poll_interval_seconds: float = 0.25,
        wait_timeout_seconds: float = 120,
        max_idempotency_records: int = _MAX_RUNTIME_IDEMPOTENCY_RECORDS,
    ) -> None:
        if max_idempotency_records < 1 or max_idempotency_records > 1_024:
            raise ValueError("max_idempotency_records must be between 1 and 1024")
        self._registry = ToolRegistry()
        CompanionControlTools(
            bridge,
            companion_directory=companion_directory,
            poll_interval_seconds=poll_interval_seconds,
            wait_timeout_seconds=wait_timeout_seconds,
        ).register(self._registry)
        self._max_idempotency_records = max_idempotency_records
        self._invocations: OrderedDict[str, _RuntimeAgentInvocation] = OrderedDict()
        self._lock = asyncio.Lock()

    @property
    def registry(self) -> ToolRegistry:
        """Expose the registered specs for runtime inspection, never credentials."""

        return self._registry

    async def reconcile_build(
        self,
        reason_code: BrowserCompanionReloadReasonCode,
        *,
        idempotency_key: str,
    ) -> BrowserCompanionBuildReconcileResponse:
        if not isinstance(reason_code, BrowserCompanionReloadReasonCode):
            raise CompanionControlToolError("reason_code must be an allowed reload reason enum")
        if _SAFE_IDEMPOTENCY_KEY.fullmatch(idempotency_key) is None:
            raise CompanionControlInvalidIdempotencyKeyError(
                "idempotency key must contain 8 to 128 safe ASCII characters"
            )

        key_digest = hashlib.sha256(idempotency_key.encode("ascii")).hexdigest()
        async with self._lock:
            invocation = self._invocations.get(key_digest)
            if invocation is not None:
                if invocation.reason_code != reason_code:
                    raise CompanionControlIdempotencyConflictError(
                        "idempotency key was already used with a different reload reason"
                    )
                self._invocations.move_to_end(key_digest)
                task = invocation.task
            else:
                if len(self._invocations) >= self._max_idempotency_records:
                    completed_key = next(
                        (
                            retained_key
                            for retained_key, retained in self._invocations.items()
                            if retained.task.done()
                        ),
                        None,
                    )
                    if completed_key is None:
                        raise CompanionControlToolError(
                            "runtime Agent idempotency record capacity exceeded"
                        )
                    self._invocations.pop(completed_key)
                call = ToolCall(
                    id=f"runtime-reload-{key_digest}",
                    tool_name=RELOAD_VERIFIED_COMPANION_TOOL,
                    task_id=f"runtime-companion-reconcile-{key_digest[:24]}",
                    agent_role=AgentRole.EXECUTOR,
                    arguments={"reason_code": reason_code.value},
                )
                task = asyncio.create_task(
                    self._invoke_executor_tool(call),
                    name=f"tripchord-companion-reconcile-{key_digest[:12]}",
                )
                task.add_done_callback(self._observe_completed_task)
                self._invocations[key_digest] = _RuntimeAgentInvocation(
                    reason_code=reason_code,
                    task=task,
                )
        # A disconnected HTTP client must not cancel the one shared operation;
        # a retry with the same key observes the exact same terminal result.
        return await asyncio.shield(task)

    async def _invoke_executor_tool(
        self,
        call: ToolCall,
    ) -> BrowserCompanionBuildReconcileResponse:
        receipt = await self._registry.invoke(call)
        if not self._registry.verify_receipt(call, receipt):
            raise CompanionControlToolError("runtime Agent tool receipt verification failed")
        try:
            return BrowserCompanionBuildReconcileResponse.model_validate(receipt.output)
        except ValidationError as exc:
            raise CompanionControlToolError(
                "runtime Agent tool returned output outside the sanitized response contract"
            ) from exc

    @staticmethod
    def _observe_completed_task(
        task: asyncio.Task[BrowserCompanionBuildReconcileResponse],
    ) -> None:
        # Retrieval prevents a disconnected HTTP caller from leaving an
        # unobserved task exception. Awaiting the retained task still returns
        # or raises the same stable terminal result for an idempotent retry.
        if not task.cancelled():
            task.exception()


class BrowserCompanionRuntimeSupervisor:
    """Opt-in background supervisor for verified build reconciliation.

    A control-capable runtime identity is a bootstrap prerequisite.  Legacy
    workers that do not report one are observed as a wait state, not a failed
    reload.  A failed target receives a bounded number of cooldown-separated
    recovery generations; exhausting that budget suppresses the target until
    the verified build changes, preventing an automatic reload loop.
    """

    def __init__(
        self,
        bridge: CompanionControlBridge,
        reconciler: CompanionRuntimeReconciler,
        *,
        companion_directory: Path | None = None,
        poll_interval_seconds: float = 5,
        retry_cooldown_seconds: float = _DEFAULT_SUPERVISOR_RETRY_COOLDOWN_SECONDS,
        max_attempts_per_target: int = _DEFAULT_SUPERVISOR_MAX_ATTEMPTS_PER_TARGET,
        monotonic: Callable[[], float] | None = None,
    ) -> None:
        if poll_interval_seconds <= 0 or poll_interval_seconds > 300:
            raise ValueError("poll_interval_seconds must be between 0 and 300")
        if retry_cooldown_seconds <= 0 or retry_cooldown_seconds > 600:
            raise ValueError("retry_cooldown_seconds must be between 0 and 600")
        if max_attempts_per_target < 1 or max_attempts_per_target > 8:
            raise ValueError("max_attempts_per_target must be between 1 and 8")
        self._bridge = bridge
        self._reconciler = reconciler
        self._companion_directory = companion_directory or default_companion_directory()
        self._poll_interval_seconds = poll_interval_seconds
        self._retry_cooldown_seconds = retry_cooldown_seconds
        self._max_attempts_per_target = max_attempts_per_target
        self._monotonic = monotonic or time.monotonic
        self._run_lock = asyncio.Lock()
        self._stop_event = asyncio.Event()
        self._task: asyncio.Task[None] | None = None
        self._failed_target_sha256: str | None = None
        self._tracked_target_sha256: str | None = None
        self._target_attempt_count = 0
        self._retry_not_before = 0.0
        self._last_outcome = "not_started"
        self._last_failure_code: str | None = None
        self._last_reconcile_result: BrowserCompanionBuildReconcileResponse | None = None
        self._attempt_count = 0

    @property
    def running(self) -> bool:
        return self._task is not None and not self._task.done()

    @property
    def last_outcome(self) -> str:
        return self._last_outcome

    @property
    def last_failure_code(self) -> str | None:
        return self._last_failure_code

    @property
    def failed_target_sha256(self) -> str | None:
        return self._failed_target_sha256

    @property
    def attempt_count(self) -> int:
        return self._attempt_count

    @property
    def last_reconcile_result(self) -> BrowserCompanionBuildReconcileResponse | None:
        return self._last_reconcile_result

    def start(self) -> None:
        if self.running:
            return
        self._stop_event.clear()
        self._task = asyncio.create_task(
            self._run_forever(),
            name="tripchord-browser-companion-runtime-supervisor",
        )

    async def close(self) -> None:
        task = self._task
        if task is None:
            return
        self._stop_event.set()
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
        finally:
            self._task = None

    async def run_once(self) -> str:
        async with self._run_lock:
            try:
                target = verified_companion_build_identity(self._companion_directory)
            except CompanionControlToolError:
                self._last_outcome = "local_build_invalid"
                self._last_failure_code = "local_build_validation_failed"
                return self._last_outcome

            status = await self._bridge.companion_status()
            candidates = tuple(
                companion
                for companion in status.companions
                if companion.is_fresh
                and companion.companion_id.startswith("chrome-mv3-")
                and companion.build_identity is not None
                and companion.build_identity.protocol_version
                == COMPANION_CONTROL_PROTOCOL_VERSION
                and companion.runtime_instance_id is not None
            )
            if len(candidates) != 1:
                self._last_outcome = "waiting_for_control_capable_companion"
                self._last_failure_code = None
                return self._last_outcome
            current = candidates[0].build_identity
            if current is None:  # narrowed above; retained as a fail-closed type guard
                self._last_outcome = "waiting_for_control_capable_companion"
                self._last_failure_code = None
                return self._last_outcome
            if hmac.compare_digest(current.build_sha256, target.build_sha256):
                self._reset_target_retry_state()
                self._last_outcome = "already_current"
                self._last_failure_code = None
                return self._last_outcome

            if self._tracked_target_sha256 is None or not hmac.compare_digest(
                self._tracked_target_sha256,
                target.build_sha256,
            ):
                self._tracked_target_sha256 = target.build_sha256
                self._target_attempt_count = 0
                self._retry_not_before = 0.0
                self._failed_target_sha256 = None
                self._last_failure_code = None
                self._last_reconcile_result = None
            if self._target_attempt_count >= self._max_attempts_per_target:
                self._failed_target_sha256 = target.build_sha256
                self._last_outcome = "failed_target_exhausted"
                return self._last_outcome
            if self._target_attempt_count > 0 and self._monotonic() < self._retry_not_before:
                self._failed_target_sha256 = target.build_sha256
                self._last_outcome = "failed_target_cooldown"
                return self._last_outcome

            recovery_generation = self._target_attempt_count + 1
            self._target_attempt_count = recovery_generation
            self._attempt_count += 1
            try:
                result = await self._reconciler.reconcile_build(
                    BrowserCompanionReloadReasonCode.COMPANION_BUILD_CHANGED,
                    idempotency_key=(
                        f"supervisor-{target.build_sha256}-{recovery_generation}"
                    ),
                )
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                self._failed_target_sha256 = target.build_sha256
                self._retry_not_before = self._monotonic() + self._retry_cooldown_seconds
                self._last_outcome = "reload_failed"
                self._last_failure_code = type(exc).__name__
                return self._last_outcome

            self._reset_target_retry_state()
            self._last_reconcile_result = result
            self._last_outcome = result.state
            self._last_failure_code = None
            return self._last_outcome

    def _reset_target_retry_state(self) -> None:
        self._failed_target_sha256 = None
        self._tracked_target_sha256 = None
        self._target_attempt_count = 0
        self._retry_not_before = 0.0

    async def _run_forever(self) -> None:
        while not self._stop_event.is_set():
            try:
                await self.run_once()
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                # Status is deliberately class-only so a provider/bridge error
                # cannot leak a URL, credential or response body into diagnostics.
                self._last_outcome = "supervisor_check_failed"
                self._last_failure_code = type(exc).__name__
            try:
                await asyncio.wait_for(
                    self._stop_event.wait(),
                    timeout=self._poll_interval_seconds,
                )
            except TimeoutError:
                continue
