from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

import pytest
from tripchord.agents.companion_control_tools import (
    COMPANION_RELEASE_SEAL_RELATIVE_PATH,
    CompanionControlToolError,
    companion_release_seal_bytes,
    verified_companion_build_identity,
)

from scripts import browser_companion_release_gate as release_gate

BUILD_ALLOWLIST = (
    "manifest.json",
    "popup.html",
    "popup.css",
    "popup.js",
    "offscreen.html",
    "src/background.js",
    "src/content.js",
    "src/offscreen.js",
    "src/parser.js",
)


def _build_sha256(companion: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in BUILD_ALLOWLIST:
        payload = (companion / relative_path).read_bytes()
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(str(len(payload)).encode("ascii"))
        digest.update(b"\0")
        digest.update(payload)
        digest.update(b"\0")
    return digest.hexdigest()


def _write_repository_fixture(repository: Path) -> tuple[Path, str]:
    companion = repository / "apps" / "browser-companion"
    (companion / "src").mkdir(parents=True)
    payloads = {
        "manifest.json": json.dumps({"version": "9.8.7"}),
        "popup.html": "popup html",
        "popup.css": "popup css",
        "popup.js": "popup js",
        "offscreen.html": "offscreen html",
        "src/background.js": 'const CONTENT_RUNTIME_VERSION = "fixture-runtime-1";',
        "src/content.js": "content js",
        "src/offscreen.js": "offscreen js",
        "src/parser.js": "parser js",
    }
    for relative_path, payload in payloads.items():
        path = companion / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(payload, encoding="utf-8")
    build_sha256 = _build_sha256(companion)
    identity = {
        "protocol_version": "tripchord-companion-control-v1",
        "manifest_version": "9.8.7",
        "build_sha256": build_sha256,
        "content_runtime_version": "fixture-runtime-1",
    }
    (companion / "src" / "build-meta.js").write_text(
        "// Generated by scripts/update-build-meta.mjs. Do not edit by hand.\n"
        "globalThis.TRIPCHORD_COMPANION_BUILD_META = "
        f"Object.freeze({json.dumps(identity, indent=2)});\n",
        encoding="utf-8",
    )
    seal_path = companion / COMPANION_RELEASE_SEAL_RELATIVE_PATH
    seal_path.write_bytes(companion_release_seal_bytes(companion))
    seal_path.chmod(0o600)
    return companion, build_sha256


def test_gate_accepts_exact_current_build_metadata(tmp_path: Path) -> None:
    _, build_sha256 = _write_repository_fixture(tmp_path)

    assert release_gate.verify_build_metadata(tmp_path) == build_sha256


def test_gate_fails_closed_on_stale_metadata_before_running_contracts(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    companion, _ = _write_repository_fixture(tmp_path)
    metadata_path = companion / "src" / "build-meta.js"
    metadata_before = metadata_path.read_bytes()
    (companion / "popup.css").write_text("changed after metadata generation", encoding="utf-8")
    launched: list[str] = []

    def unexpected_run(*args: object, **kwargs: object) -> None:
        del args, kwargs
        launched.append("subprocess")

    monkeypatch.setattr(release_gate, "_run_checked", unexpected_run)

    with pytest.raises(release_gate.ReleaseGateError, match="发布 seal 无效"):
        release_gate.run_release_gate(repository=tmp_path)

    assert launched == []
    assert metadata_path.read_bytes() == metadata_before


def test_gate_rejects_runtime_version_mismatch(tmp_path: Path) -> None:
    companion, _ = _write_repository_fixture(tmp_path)
    metadata_path = companion / "src" / "build-meta.js"
    metadata_path.write_text(
        metadata_path.read_text(encoding="utf-8").replace(
            '"content_runtime_version": "fixture-runtime-1"',
            '"content_runtime_version": "fixture-runtime-wrong"',
        ),
        encoding="utf-8",
    )

    with pytest.raises(release_gate.ReleaseGateError, match="runtime version"):
        release_gate.verify_build_metadata(tmp_path)


def test_gate_scrubs_runtime_secrets_from_test_environment(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    for name in release_gate._SECRET_ENVIRONMENT_NAMES:
        monkeypatch.setenv(name, "must-not-reach-release-tests")

    environment = release_gate._test_environment()

    assert all(name not in environment for name in release_gate._SECRET_ENVIRONMENT_NAMES)
    assert environment["MODEL_PROVIDER"] == "none"
    assert environment["TRIPCHORD_BROWSER_BRIDGE_ENABLED"] == "false"


def test_default_gate_never_invokes_build_metadata_generator(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    launched: list[tuple[str, ...]] = []
    monkeypatch.setattr(release_gate, "verify_build_metadata", lambda _: "c" * 64)
    monkeypatch.setattr(
        release_gate,
        "_run_checked",
        lambda _label, command, **_kwargs: launched.append(tuple(command)),
    )

    assert release_gate.run_release_gate(repository=tmp_path) == "c" * 64

    assert launched
    assert all("update-build-meta.mjs" not in command for command in launched)


def test_update_mode_keeps_candidate_unsealed_until_every_contract_passes(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    companion, build_sha256 = _write_repository_fixture(tmp_path)
    seal_path = companion / COMPANION_RELEASE_SEAL_RELATIVE_PATH
    actions: list[str] = []

    def record_run(label: str, command: tuple[str, ...], **_kwargs: object) -> None:
        assert not seal_path.exists()
        actions.append(f"run:{label}:{' '.join(command)}")

    monkeypatch.setattr(release_gate, "_run_checked", record_run)

    assert (
        release_gate.run_release_gate(repository=tmp_path, update_build_meta=True)
        == build_sha256
    )

    assert actions[0].endswith("node apps/browser-companion/scripts/update-build-meta.mjs")
    assert len(actions) == 1 + len(release_gate._JS_CONTRACTS) + 1
    assert seal_path.exists()
    assert verified_companion_build_identity(companion).build_sha256 == build_sha256


def test_update_failure_restores_previous_metadata_and_seal(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    companion, build_sha256 = _write_repository_fixture(tmp_path)
    metadata_path = companion / "src" / "build-meta.js"
    seal_path = companion / COMPANION_RELEASE_SEAL_RELATIVE_PATH
    metadata_before = metadata_path.read_bytes()
    seal_before = seal_path.read_bytes()
    call_count = 0

    def fail_first_contract(
        label: str,
        command: tuple[str, ...],
        **_kwargs: object,
    ) -> None:
        nonlocal call_count
        assert not seal_path.exists()
        call_count += 1
        if call_count == 2:
            raise release_gate.ReleaseGateError(f"fixture contract failure: {label}")
        assert command

    monkeypatch.setattr(release_gate, "_run_checked", fail_first_contract)

    with pytest.raises(release_gate.ReleaseGateError, match="fixture contract failure"):
        release_gate.run_release_gate(repository=tmp_path, update_build_meta=True)

    assert metadata_path.read_bytes() == metadata_before
    assert seal_path.read_bytes() == seal_before
    assert verified_companion_build_identity(companion).build_sha256 == build_sha256


def test_interruption_restores_old_release_state(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    companion, build_sha256 = _write_repository_fixture(tmp_path)
    seal_path = companion / COMPANION_RELEASE_SEAL_RELATIVE_PATH

    def interrupt(_label: str, _command: tuple[str, ...], **_kwargs: object) -> None:
        assert not seal_path.exists()
        raise KeyboardInterrupt

    monkeypatch.setattr(release_gate, "_run_checked", interrupt)

    with pytest.raises(KeyboardInterrupt):
        release_gate.run_release_gate(repository=tmp_path, update_build_meta=True)

    assert verified_companion_build_identity(companion).build_sha256 == build_sha256


def test_process_crash_after_invalidation_leaves_candidate_fail_closed(
    tmp_path: Path,
) -> None:
    companion, _ = _write_repository_fixture(tmp_path)
    seal_path = companion / COMPANION_RELEASE_SEAL_RELATIVE_PATH

    # An uncatchable process exit cannot run rollback, so the ordering invariant
    # is the safety property: seal removal is durable before candidate writes.
    release_gate._remove_release_file(seal_path)

    with pytest.raises(CompanionControlToolError, match="release seal"):
        verified_companion_build_identity(companion)


def test_atomic_writer_uses_same_directory_replace_and_exact_mode(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    target = tmp_path / "release" / "seal.json"
    replacements: list[tuple[Path, Path]] = []
    real_replace = os.replace

    def record_replace(source: str | Path, destination: str | Path) -> None:
        source_path = Path(source)
        destination_path = Path(destination)
        assert source_path.parent == destination_path.parent == target.parent
        assert source_path != destination_path
        assert not destination_path.exists()
        replacements.append((source_path, destination_path))
        real_replace(source_path, destination_path)

    monkeypatch.setattr(os, "replace", record_replace)

    release_gate._atomic_write_bytes(target, b"sealed\n", mode=0o600)

    assert replacements
    assert target.read_bytes() == b"sealed\n"
    assert target.stat().st_mode & 0o777 == 0o600
    assert list(target.parent.glob(f".{target.name}.tmp-*")) == []
