// Generated by scripts/update-build-meta.mjs. Do not edit by hand.
globalThis.TRIPCHORD_COMPANION_BUILD_META = Object.freeze({
  "protocol_version": "tripchord-companion-control-v1",
  "manifest_version": "0.1.16",
  "build_sha256": "46c74942d86e8f74f31971c4e32f35d10709d255dd7c1ed84ca2951e70878f1e",
  "content_runtime_version": "2026-08-05.18"
});
