from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import secrets
import stat
import sys
from collections.abc import Mapping, Sequence
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, quote, urlencode, urlsplit, urlunsplit

import httpx

SCHEMA_VERSION = "tripchord-live-browser-focused-sealed-evidence-v1"
CANONICALIZATION = "utf8-json-sort-keys-no-whitespace-v1"
BRIDGE_TOKEN_HEADER = "X-TripChord-Bridge-Token"
_SHA256 = re.compile(r"\A[0-9a-f]{64}\Z")
_TASK_ID = re.compile(r"\Abrowser-task-[A-Za-z0-9_-]{8,128}\Z")
_RUNTIME_INSTANCE_ID = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._:-]{15,127}\Z")
_RELOAD_REQUEST_ID = re.compile(r"\Acompanion-reload-[A-Za-z0-9_-]+\Z")
_FORBIDDEN_OUTPUT_KEYS = (
    "authorization",
    "claim_token",
    "cookie",
    "password",
    "receipt_token",
    "visible_evidence",
)
_SAFE_URL_QUERY_KEYS: dict[str, frozenset[str]] = {
    "ctrip": frozenset(
        {
            "adult",
            "barcurr",
            "checkin",
            "checkout",
            "children",
            "cityenname",
            "cityid",
            "crn",
            "curr",
            "hotelid",
            "hoteltype",
        }
    ),
    "qunar": frozenset(
        {
            "adult",
            "checkin",
            "checkout",
            "city",
            "cityurl",
            "fromdate",
            "hotelid",
            "roomnum",
            "todate",
        }
    ),
    "tongcheng": frozenset(
        {
            "adult",
            "checkin",
            "checkout",
            "cityid",
            "hotelid",
            "roomnum",
        }
    ),
}
_PROVIDER_DOMAINS: dict[str, tuple[str, ...]] = {
    "ctrip": ("ctrip.com",),
    "qunar": ("qunar.com",),
    "tongcheng": ("ly.com", "elong.com"),
}
_SOURCE_ARTIFACTS = (
    "apps/browser-companion/.tripchord-release-seal.json",
    "apps/browser-companion/src/build-meta.js",
    "scripts/capture_live_browser_evidence.py",
)
_BUILD_META_PATTERN = re.compile(
    r"\A// Generated by scripts/update-build-meta\.mjs\. Do not edit by hand\.\r?\n"
    r"globalThis\.TRIPCHORD_COMPANION_BUILD_META\s*=\s*"
    r"Object\.freeze\((?P<payload>\{[\s\S]*\})\);\s*\Z"
)


class EvidenceCaptureError(RuntimeError):
    pass


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Seal existing terminal Browser Bridge tasks without submitting work, "
            "operating Chrome, or calling a model."
        )
    )
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument("--bridge-token-file", type=Path)
    parser.add_argument("--task-id", action="append", default=[])
    parser.add_argument("--companion-id")
    parser.add_argument(
        "--skipped-lodging-provider",
        action="append",
        default=[],
        help="bind an explicit user scope decision without granting price coverage",
    )
    parser.add_argument("--source-summary", type=Path)
    parser.add_argument(
        "--summary-output",
        type=Path,
        help="optionally write a compact run summary derived from the sealed artifact",
    )
    parser.add_argument("--output", type=Path)
    parser.add_argument("--repository", type=Path, default=_repository())
    parser.add_argument(
        "--verify",
        type=Path,
        help="verify an existing sealed artifact without contacting the API",
    )
    return parser.parse_args()


def _repository() -> Path:
    return Path(__file__).resolve().parents[1]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _canonical_sha256(value: object) -> str:
    return hashlib.sha256(_canonical_bytes(value)).hexdigest()


def _file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _mapping(value: object, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise EvidenceCaptureError(f"{label} must be an object")
    return value


def _sequence(value: object, label: str) -> Sequence[Any]:
    if not isinstance(value, list | tuple):
        raise EvidenceCaptureError(f"{label} must be an array")
    return value


def _string(value: object, label: str, *, maximum: int = 512) -> str:
    if not isinstance(value, str) or not value or len(value) > maximum:
        raise EvidenceCaptureError(f"{label} must be a non-empty bounded string")
    return value


def _optional_string(value: object, label: str, *, maximum: int = 512) -> str | None:
    if value is None:
        return None
    return _string(value, label, maximum=maximum)


def _boolean(value: object, label: str) -> bool:
    if not isinstance(value, bool):
        raise EvidenceCaptureError(f"{label} must be boolean")
    return value


def _integer(value: object, label: str, *, minimum: int = 0) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise EvidenceCaptureError(f"{label} must be an integer >= {minimum}")
    return value


def _digest(value: object, label: str) -> str:
    normalized = _string(value, label, maximum=64).lower()
    if not _SHA256.fullmatch(normalized):
        raise EvidenceCaptureError(f"{label} must be a lowercase SHA-256 digest")
    return normalized


def _decimal_text(value: object, label: str) -> str:
    if isinstance(value, bool) or not isinstance(value, int | float | str):
        raise EvidenceCaptureError(f"{label} must be numeric")
    try:
        amount = Decimal(str(value))
    except InvalidOperation as exc:
        raise EvidenceCaptureError(f"{label} must be numeric") from exc
    if not amount.is_finite() or amount < 0:
        raise EvidenceCaptureError(f"{label} must be a non-negative finite amount")
    normalized = format(amount, "f")
    if "." in normalized:
        normalized = normalized.rstrip("0").rstrip(".")
    return normalized or "0"


def _validate_base_url(value: str) -> str:
    parsed = urlsplit(value)
    if (
        parsed.scheme != "http"
        or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or parsed.path not in {"", "/"}
    ):
        raise EvidenceCaptureError("base URL must be a plain loopback HTTP origin")
    return value.rstrip("/")


def _secure_token(path: Path) -> str:
    try:
        file_stat = path.lstat()
    except FileNotFoundError as exc:
        raise EvidenceCaptureError("bridge token file does not exist") from exc
    if stat.S_ISLNK(file_stat.st_mode) or not stat.S_ISREG(file_stat.st_mode):
        raise EvidenceCaptureError("bridge token path must be a regular file, not a symlink")
    if file_stat.st_uid != os.getuid() or stat.S_IMODE(file_stat.st_mode) != 0o600:
        raise EvidenceCaptureError("bridge token file must be owned by this user with mode 0600")
    if file_stat.st_size > 4096:
        raise EvidenceCaptureError("bridge token file is unexpectedly large")
    token = path.read_text(encoding="utf-8").strip()
    if not 32 <= len(token) <= 256 or any(character.isspace() for character in token):
        raise EvidenceCaptureError("bridge token file contains an invalid token shape")
    return token


def _fetch_json(
    client: httpx.Client,
    path: str,
    *,
    bridge_token: str | None = None,
) -> dict[str, Any]:
    headers = {BRIDGE_TOKEN_HEADER: bridge_token} if bridge_token is not None else None
    try:
        response = client.get(path, headers=headers)
    except httpx.HTTPError as exc:
        raise EvidenceCaptureError(f"read-only GET failed for {path}") from exc
    if response.is_redirect:
        raise EvidenceCaptureError(f"read-only GET refused a redirect for {path}")
    if response.status_code != 200:
        raise EvidenceCaptureError(
            f"read-only GET returned HTTP {response.status_code} for {path}"
        )
    try:
        payload = response.json()
    except ValueError as exc:
        raise EvidenceCaptureError(f"read-only GET returned invalid JSON for {path}") from exc
    if not isinstance(payload, dict):
        raise EvidenceCaptureError(f"read-only GET returned a non-object for {path}")
    return payload


def _normalize_query(raw: object) -> dict[str, object]:
    query = _mapping(raw, "task.query")
    options = _mapping(query.get("options", {}), "task.query.options")
    allowed_options = {
        "segment",
        "expected_package_area",
        "expected_lodging_place_key",
        "__tripchord_allow_recent_quote_reuse",
    }
    unexpected = set(options) - allowed_options
    if unexpected:
        raise EvidenceCaptureError(f"task.query.options has unsealed fields: {sorted(unexpected)}")
    return {
        "destination": _string(query.get("destination"), "task.query.destination"),
        "start_date": _string(query.get("start_date"), "task.query.start_date", maximum=10),
        "end_date": _string(query.get("end_date"), "task.query.end_date", maximum=10),
        "adults": _integer(query.get("adults"), "task.query.adults", minimum=1),
        "rooms": _integer(query.get("rooms"), "task.query.rooms", minimum=1),
        "currency": _string(query.get("currency"), "task.query.currency", maximum=3).upper(),
        "segment": _string(options.get("segment"), "task.query.options.segment"),
        "expected_package_area": _string(
            options.get("expected_package_area"),
            "task.query.options.expected_package_area",
        ),
        "expected_lodging_place_key": _string(
            options.get("expected_lodging_place_key"),
            "task.query.options.expected_lodging_place_key",
        ),
        "recent_quote_reuse_allowed": _boolean(
            options.get("__tripchord_allow_recent_quote_reuse"),
            "task.query.options.__tripchord_allow_recent_quote_reuse",
        ),
    }


def _provider_host_allowed(provider: str, host: str) -> bool:
    return any(
        host == domain or host.endswith(f".{domain}")
        for domain in _PROVIDER_DOMAINS.get(provider, ())
    )


def _sanitize_page_url(raw: object, provider: str, label: str) -> str:
    value = _string(raw, label, maximum=4096)
    parsed = urlsplit(value)
    host = (parsed.hostname or "").lower()
    if (
        parsed.scheme != "https"
        or not _provider_host_allowed(provider, host)
        or parsed.username is not None
        or parsed.password is not None
    ):
        raise EvidenceCaptureError(f"{label} is not an allowed provider HTTPS URL")
    safe_keys = _SAFE_URL_QUERY_KEYS[provider]
    safe_query: list[tuple[str, str]] = []
    for key, item in parse_qsl(parsed.query, keep_blank_values=True):
        if key.lower() in safe_keys and len(key) <= 64 and len(item) <= 256:
            safe_query.append((key, item))
    safe_query.sort(key=lambda pair: (pair[0].lower(), pair[0], pair[1]))
    return urlunsplit(
        (
            "https",
            host,
            parsed.path or "/",
            urlencode(safe_query, doseq=True),
            "",
        )
    )


def _normalize_quote(raw: object, provider: str) -> dict[str, object]:
    quote_payload = _mapping(raw, "task.quote")
    quote_provider = _string(quote_payload.get("provider"), "task.quote.provider")
    if quote_provider != provider:
        raise EvidenceCaptureError("task quote provider does not match its source task")
    kind = _string(quote_payload.get("kind"), "task.quote.kind")
    if kind != "lodging":
        raise EvidenceCaptureError("focused lodging evidence cannot contain non-lodging quotes")
    details = _mapping(quote_payload.get("details"), "task.quote.details")
    property_id = _string(
        details.get("property_id"), "task.quote.details.property_id", maximum=128
    )
    property_name = _string(
        details.get("property_name"), "task.quote.details.property_name", maximum=256
    )
    taxes = quote_payload.get("taxes_included")
    if taxes is not None and not isinstance(taxes, bool):
        raise EvidenceCaptureError("task.quote.taxes_included must be boolean or null")
    return {
        "provider": quote_provider,
        "kind": kind,
        "page_url": _sanitize_page_url(
            quote_payload.get("page_url"), provider, "task.quote.page_url"
        ),
        "captured_at": _string(
            quote_payload.get("captured_at"), "task.quote.captured_at", maximum=40
        ),
        "evidence_sha256": _digest(
            quote_payload.get("evidence_sha256"), "task.quote.evidence_sha256"
        ),
        "parser_version": _string(
            quote_payload.get("parser_version"), "task.quote.parser_version", maximum=64
        ),
        "amount": _decimal_text(quote_payload.get("amount"), "task.quote.amount"),
        "currency": _string(
            quote_payload.get("currency"), "task.quote.currency", maximum=3
        ).upper(),
        "price_basis": _string(
            quote_payload.get("price_basis"), "task.quote.price_basis", maximum=32
        ),
        "taxes_included": taxes,
        "price_finality": _string(
            details.get("price_finality"), "task.quote.details.price_finality", maximum=64
        ),
        "availability": _string(
            details.get("availability"), "task.quote.details.availability", maximum=64
        ),
        "property": {"id": property_id, "name": property_name},
    }


def _normalize_url_shape(raw: object, label: str) -> dict[str, object]:
    shape = _mapping(raw, label)
    host = _string(shape.get("host"), f"{label}.host", maximum=255).lower()
    if not _provider_host_allowed("qunar", host):
        raise EvidenceCaptureError(f"{label}.host is outside the Qunar domain boundary")
    query_keys = [
        _string(item, f"{label}.query_keys[]", maximum=64)
        for item in _sequence(shape.get("query_keys", []), f"{label}.query_keys")
    ]
    if len(query_keys) > 16:
        raise EvidenceCaptureError(f"{label}.query_keys exceeds the bounded diagnostic")
    return {
        "parseable": _boolean(shape.get("parseable"), f"{label}.parseable"),
        "scheme": _string(shape.get("scheme"), f"{label}.scheme", maximum=8),
        "host": host,
        "path_shape": _string(
            shape.get("path_shape"), f"{label}.path_shape", maximum=512
        ),
        "query_keys": query_keys,
        "query_keys_truncated": _boolean(
            shape.get("query_keys_truncated"), f"{label}.query_keys_truncated"
        ),
        "has_fragment": _boolean(shape.get("has_fragment"), f"{label}.has_fragment"),
    }


def _normalize_navigation_diagnostic(raw: object) -> dict[str, object]:
    diagnostic = _mapping(raw, "failure.details.navigation_diagnostic")
    trace: list[dict[str, object]] = []
    for index, item in enumerate(
        _sequence(
            diagnostic.get("redirect_trace", []),
            "failure.details.navigation_diagnostic.redirect_trace",
        )
    ):
        if index >= 8:
            raise EvidenceCaptureError("Qunar redirect trace exceeds eight bounded entries")
        entry = _mapping(item, f"failure.redirect_trace[{index}]")
        status_value = entry.get("status")
        trace.append(
            {
                "sequence": _integer(entry.get("sequence"), f"redirect_trace[{index}].sequence"),
                "phase": _string(entry.get("phase"), f"redirect_trace[{index}].phase"),
                "tab_role": _string(entry.get("tab_role"), f"redirect_trace[{index}].tab_role"),
                "status": _optional_string(
                    status_value, f"redirect_trace[{index}].status", maximum=64
                ),
                "transient": _boolean(
                    entry.get("transient"), f"redirect_trace[{index}].transient"
                ),
                "url": _normalize_url_shape(entry.get("url"), f"redirect_trace[{index}].url"),
            }
        )
    return {
        "provider": _string(diagnostic.get("provider"), "navigation.provider"),
        "vertical": _string(diagnostic.get("vertical"), "navigation.vertical"),
        "stage": _string(diagnostic.get("stage"), "navigation.stage"),
        "reason": _string(diagnostic.get("reason"), "navigation.reason"),
        "rejected_url": _normalize_url_shape(
            diagnostic.get("rejected_url"), "navigation.rejected_url"
        ),
        "login_return_url": _normalize_url_shape(
            diagnostic.get("login_return_url"), "navigation.login_return_url"
        ),
        "redirect_trace": trace,
    }


def _normalize_browser_isolation(raw: object) -> dict[str, object]:
    isolation = _mapping(raw, "failure.details.browser_isolation")
    string_fields = (
        "scope",
        "owner",
        "window_type",
        "requested_window_state",
        "cleanup_policy",
        "fallback_policy",
        "lifecycle_state",
        "observed_window_state",
    )
    boolean_fields = (
        "requested_focused",
        "tab_active_in_isolated_window",
        "reused_user_window",
        "minimized",
        "observed_focused",
    )
    result: dict[str, object] = {
        field: _string(isolation.get(field), f"browser_isolation.{field}")
        for field in string_fields
    }
    result.update(
        {
            field: _boolean(isolation.get(field), f"browser_isolation.{field}")
            for field in boolean_fields
        }
    )
    result["observed_active_tab_count"] = _integer(
        isolation.get("observed_active_tab_count"),
        "browser_isolation.observed_active_tab_count",
    )
    return result


def _normalize_stage_trace(raw: object) -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for index, item in enumerate(_sequence(raw, "failure.details.stage_trace")):
        if index >= 16:
            raise EvidenceCaptureError("stage trace exceeds sixteen bounded entries")
        entry = _mapping(item, f"stage_trace[{index}]")
        result.append(
            {
                "sequence": _integer(entry.get("sequence"), f"stage_trace[{index}].sequence"),
                "stage": _string(entry.get("stage"), f"stage_trace[{index}].stage"),
                "status": _string(entry.get("status"), f"stage_trace[{index}].status"),
                "budget_ms": _integer(
                    entry.get("budget_ms"), f"stage_trace[{index}].budget_ms"
                ),
                "elapsed_ms": _integer(
                    entry.get("elapsed_ms"), f"stage_trace[{index}].elapsed_ms"
                ),
                "remaining_lease_ms": _integer(
                    entry.get("remaining_lease_ms"),
                    f"stage_trace[{index}].remaining_lease_ms",
                ),
                "failure_code": _optional_string(
                    entry.get("failure_code"),
                    f"stage_trace[{index}].failure_code",
                    maximum=64,
                ),
            }
        )
    return result


def _normalize_failure(raw: object, provider: str) -> dict[str, object]:
    failure = _mapping(raw, "task.failure")
    result: dict[str, object] = {
        "code": _string(failure.get("code"), "task.failure.code", maximum=64),
        "retryable": _boolean(failure.get("retryable"), "task.failure.retryable"),
        "captured_at": _string(
            failure.get("captured_at"), "task.failure.captured_at", maximum=40
        ),
        "page_url": (
            _sanitize_page_url(failure.get("page_url"), provider, "task.failure.page_url")
            if failure.get("page_url") is not None
            else None
        ),
    }
    details = _mapping(failure.get("details", {}), "task.failure.details")
    if provider == "qunar" and result["code"] == "login_required":
        result["navigation_diagnostic"] = _normalize_navigation_diagnostic(
            details.get("navigation_diagnostic")
        )
        result["browser_isolation"] = _normalize_browser_isolation(
            details.get("browser_isolation")
        )
        lease = _mapping(details.get("lease_timing"), "failure.details.lease_timing")
        result["lease_timing"] = {
            "deadline_source": _string(
                lease.get("deadline_source"), "lease_timing.deadline_source"
            ),
            "lease_duration_ms": _integer(
                lease.get("lease_duration_ms"), "lease_timing.lease_duration_ms"
            ),
            "completion_reserve_ms": _integer(
                lease.get("completion_reserve_ms"), "lease_timing.completion_reserve_ms"
            ),
            "lease_expires_at": _string(
                lease.get("lease_expires_at"), "lease_timing.lease_expires_at", maximum=40
            ),
            "work_deadline_at": _string(
                lease.get("work_deadline_at"), "lease_timing.work_deadline_at", maximum=40
            ),
        }
        result["stage_trace"] = _normalize_stage_trace(details.get("stage_trace"))
    return result


def _normalize_task(raw: object, expected_task_id: str) -> dict[str, object]:
    task = _mapping(raw, f"task[{expected_task_id}]")
    task_id = _string(task.get("id"), "task.id", maximum=160)
    if task_id != expected_task_id or not _TASK_ID.fullmatch(task_id):
        raise EvidenceCaptureError("bridge returned an unexpected task ID")
    provider = _string(task.get("provider"), "task.provider", maximum=32)
    if provider not in _PROVIDER_DOMAINS:
        raise EvidenceCaptureError("focused evidence contains an unsupported provider")
    kind = _string(task.get("kind"), "task.kind", maximum=32)
    if kind != "lodging":
        raise EvidenceCaptureError("focused evidence only accepts lodging tasks")
    state = _string(task.get("state"), "task.state", maximum=32)
    if state not in {"succeeded", "blocked", "failed", "cancelled"}:
        raise EvidenceCaptureError("focused evidence requires terminal bridge tasks")
    quotes = [
        _normalize_quote(item, provider)
        for item in _sequence(task.get("quotes", []), "task.quotes")
    ]
    quotes.sort(
        key=lambda quote_item: (
            str(_mapping(quote_item["property"], "quote.property")["id"]),
            Decimal(str(quote_item["amount"])),
            str(quote_item["evidence_sha256"]),
        )
    )
    failure_raw = task.get("failure")
    failure = _normalize_failure(failure_raw, provider) if failure_raw is not None else None
    if state == "succeeded" and (not quotes or failure is not None):
        raise EvidenceCaptureError("successful task must have quotes and no failure")
    if state != "succeeded" and (quotes or failure is None):
        raise EvidenceCaptureError("non-success terminal task must have one failure and no quotes")
    reused = task.get("reused_from_task_id")
    return {
        "task_id": task_id,
        "provider": provider,
        "kind": kind,
        "query": _normalize_query(task.get("query")),
        "state": state,
        "created_at": _string(task.get("created_at"), "task.created_at", maximum=40),
        "updated_at": _string(task.get("updated_at"), "task.updated_at", maximum=40),
        "attempt_count": _integer(task.get("attempt_count"), "task.attempt_count"),
        "reused_from_task_id": _optional_string(
            reused, "task.reused_from_task_id", maximum=160
        ),
        "inflight_coalesced": _boolean(
            task.get("inflight_coalesced"), "task.inflight_coalesced"
        ),
        "quote_count": len(quotes),
        "quotes": quotes,
        "failure": failure,
    }


def _normalize_build_identity(raw: object, label: str) -> dict[str, str]:
    identity = _mapping(raw, label)
    return {
        "protocol_version": _string(
            identity.get("protocol_version"), f"{label}.protocol_version", maximum=64
        ),
        "manifest_version": _string(
            identity.get("manifest_version"), f"{label}.manifest_version", maximum=64
        ),
        "build_sha256": _digest(identity.get("build_sha256"), f"{label}.build_sha256"),
        "content_runtime_version": _string(
            identity.get("content_runtime_version"),
            f"{label}.content_runtime_version",
            maximum=64,
        ),
    }


def _normalize_companion(raw: object, companion_id: str | None) -> dict[str, object]:
    status = _mapping(raw, "companion status")
    companions = [
        _mapping(item, "companion status entry")
        for item in _sequence(status.get("companions"), "companion status.companions")
    ]
    if companion_id is None:
        if len(companions) != 1:
            raise EvidenceCaptureError("companion ID is required when status is not singular")
        selected = companions[0]
    else:
        matches = [item for item in companions if item.get("companion_id") == companion_id]
        if len(matches) != 1:
            raise EvidenceCaptureError("requested companion ID is not uniquely present")
        selected = matches[0]
    runtime_id = _string(
        selected.get("runtime_instance_id"), "companion.runtime_instance_id", maximum=128
    )
    if not _RUNTIME_INSTANCE_ID.fullmatch(runtime_id):
        raise EvidenceCaptureError("companion runtime instance ID has an invalid shape")
    providers = sorted(
        {
            _string(item, "companion.providers[]", maximum=32)
            for item in _sequence(selected.get("providers"), "companion.providers")
        }
    )
    return {
        "companion_id": _string(
            selected.get("companion_id"), "companion.companion_id", maximum=128
        ),
        "providers": providers,
        "build_identity": _normalize_build_identity(
            selected.get("build_identity"), "companion.build_identity"
        ),
        "runtime_instance_id": runtime_id,
    }


def _normalize_reconcile(raw: object) -> dict[str, object]:
    receipt = _mapping(raw, "runtime.browser_companion_last_reconcile")
    request_id = _optional_string(
        receipt.get("request_id"), "reconcile.request_id", maximum=128
    )
    if request_id is not None and not _RELOAD_REQUEST_ID.fullmatch(request_id):
        raise EvidenceCaptureError("reconcile request ID has an invalid shape")
    old_runtime = _string(
        receipt.get("old_runtime_instance_id"),
        "reconcile.old_runtime_instance_id",
        maximum=128,
    )
    new_runtime = _string(
        receipt.get("new_runtime_instance_id"),
        "reconcile.new_runtime_instance_id",
        maximum=128,
    )
    if not _RUNTIME_INSTANCE_ID.fullmatch(old_runtime) or not _RUNTIME_INSTANCE_ID.fullmatch(
        new_runtime
    ):
        raise EvidenceCaptureError("reconcile runtime instance ID has an invalid shape")
    timings = _mapping(receipt.get("timings"), "reconcile.timings")
    return {
        "request_id": request_id,
        "companion_id": _string(
            receipt.get("companion_id"), "reconcile.companion_id", maximum=128
        ),
        "state": _string(receipt.get("state"), "reconcile.state", maximum=32),
        "old_build_sha256": _digest(
            receipt.get("old_build_sha256"), "reconcile.old_build_sha256"
        ),
        "target_build_sha256": _digest(
            receipt.get("target_build_sha256"), "reconcile.target_build_sha256"
        ),
        "old_runtime_instance_id": old_runtime,
        "new_runtime_instance_id": new_runtime,
        "timings": {
            "requested_at": _string(
                timings.get("requested_at"), "reconcile.timings.requested_at", maximum=40
            ),
            "updated_at": _string(
                timings.get("updated_at"), "reconcile.timings.updated_at", maximum=40
            ),
            "accepted_at": _optional_string(
                timings.get("accepted_at"), "reconcile.timings.accepted_at", maximum=40
            ),
            "applied_at": _optional_string(
                timings.get("applied_at"), "reconcile.timings.applied_at", maximum=40
            ),
            "elapsed_ms": _integer(
                timings.get("elapsed_ms"), "reconcile.timings.elapsed_ms"
            ),
        },
    }


def _normalize_runtime(raw: object) -> dict[str, object]:
    runtime = _mapping(raw, "agent runtime")
    reconcile = _normalize_reconcile(runtime.get("browser_companion_last_reconcile"))
    return {
        "codex_runtime_dependency": _boolean(
            runtime.get("codex_runtime_dependency"), "runtime.codex_runtime_dependency"
        ),
        "chatgpt_runtime_dependency": _boolean(
            runtime.get("chatgpt_runtime_dependency"), "runtime.chatgpt_runtime_dependency"
        ),
        "model_enabled": _boolean(runtime.get("model_enabled"), "runtime.model_enabled"),
        "model_required": _boolean(runtime.get("model_required"), "runtime.model_required"),
        "model_provider": _string(
            runtime.get("model_provider"), "runtime.model_provider", maximum=64
        ),
        "primary_model": _string(
            runtime.get("primary_model"), "runtime.primary_model", maximum=128
        ),
        "fast_model": _string(runtime.get("fast_model"), "runtime.fast_model", maximum=128),
        "browser_companion_control_enabled": _boolean(
            runtime.get("browser_companion_control_enabled"),
            "runtime.browser_companion_control_enabled",
        ),
        "browser_companion_auto_reload_enabled": _boolean(
            runtime.get("browser_companion_auto_reload_enabled"),
            "runtime.browser_companion_auto_reload_enabled",
        ),
        "browser_companion_supervisor_running": _boolean(
            runtime.get("browser_companion_supervisor_running"),
            "runtime.browser_companion_supervisor_running",
        ),
        "browser_companion_supervisor_outcome": _string(
            runtime.get("browser_companion_supervisor_outcome"),
            "runtime.browser_companion_supervisor_outcome",
            maximum=64,
        ),
        "browser_companion_supervisor_attempt_count": _integer(
            runtime.get("browser_companion_supervisor_attempt_count"),
            "runtime.browser_companion_supervisor_attempt_count",
        ),
        "browser_companion_last_reconcile": reconcile,
    }


def _source_artifact_receipts(
    repository: Path,
    source_summary: Path | None,
) -> list[dict[str, str]]:
    resolved_repository = repository.resolve()
    try:
        from tripchord.agents.companion_control_tools import (
            COMPANION_BUILD_FILE_ALLOWLIST,
        )
    except ImportError:
        api_source = repository / "apps" / "api" / "src"
        if str(api_source) not in sys.path:
            sys.path.insert(0, str(api_source))
        from tripchord.agents.companion_control_tools import (
            COMPANION_BUILD_FILE_ALLOWLIST,
        )
    relative_paths = {
        *_SOURCE_ARTIFACTS,
        *(f"apps/browser-companion/{item}" for item in COMPANION_BUILD_FILE_ALLOWLIST),
    }
    paths = [repository / item for item in sorted(relative_paths)]
    if source_summary is not None:
        paths.append(source_summary)
    receipts: list[dict[str, str]] = []
    for path in paths:
        if path.is_symlink() or not path.is_file():
            raise EvidenceCaptureError(f"source artifact is not a regular file: {path}")
        resolved = path.resolve()
        if not resolved.is_relative_to(resolved_repository):
            raise EvidenceCaptureError(f"source artifact is outside the repository: {path}")
        receipts.append(
            {
                "path": resolved.relative_to(resolved_repository).as_posix(),
                "sha256": _file_sha256(resolved),
            }
        )
    receipts.sort(key=lambda item: item["path"])
    return receipts


def _release_binding(repository: Path) -> dict[str, object]:
    api_source = repository / "apps" / "api" / "src"
    if str(api_source) not in sys.path:
        sys.path.insert(0, str(api_source))
    try:
        from pydantic import ValidationError
        from tripchord.agents.companion_control_tools import (
            BrowserCompanionReleaseSeal,
            companion_build_sha256,
        )
        from tripchord.providers.browser_bridge import BrowserCompanionBuildIdentity
    except ImportError as exc:
        raise EvidenceCaptureError("cannot import the Companion release schemas") from exc
    companion_directory = repository / "apps" / "browser-companion"
    seal_path = companion_directory / ".tripchord-release-seal.json"
    meta_path = companion_directory / "src" / "build-meta.js"
    for path, label in ((seal_path, "release seal"), (meta_path, "build metadata")):
        try:
            file_stat = path.lstat()
        except FileNotFoundError as exc:
            raise EvidenceCaptureError(f"Companion {label} is missing") from exc
        if stat.S_ISLNK(file_stat.st_mode) or not stat.S_ISREG(file_stat.st_mode):
            raise EvidenceCaptureError(f"Companion {label} must be a regular file")
    seal_stat = seal_path.stat()
    if seal_stat.st_uid != os.getuid() or stat.S_IMODE(seal_stat.st_mode) != 0o600:
        raise EvidenceCaptureError("historical release seal must be current-user 0600")
    try:
        seal = BrowserCompanionReleaseSeal.model_validate_json(seal_path.read_bytes())
        meta_bytes = meta_path.read_bytes()
        match = _BUILD_META_PATTERN.fullmatch(meta_bytes.decode("utf-8"))
        if match is None:
            raise EvidenceCaptureError("historical build metadata is not canonical")
        identity = BrowserCompanionBuildIdentity.model_validate_json(match.group("payload"))
    except (UnicodeError, ValidationError) as exc:
        raise EvidenceCaptureError("historical Companion release receipt is invalid") from exc
    if _file_sha256(meta_path) != seal.build_meta_sha256:
        raise EvidenceCaptureError("historical release seal no longer binds build metadata")
    sealed_identity = {
        "protocol_version": seal.protocol_version,
        "manifest_version": seal.manifest_version,
        "build_sha256": seal.build_sha256,
        "content_runtime_version": seal.content_runtime_version,
    }
    if identity.model_dump(mode="json") != sealed_identity:
        raise EvidenceCaptureError("historical release seal and build metadata disagree")
    try:
        current_worktree_build_sha256 = companion_build_sha256(companion_directory)
    except (OSError, RuntimeError) as exc:
        raise EvidenceCaptureError("cannot hash the current Companion worktree") from exc
    return {
        "sealed_identity": sealed_identity,
        "release_seal_sha256": _file_sha256(seal_path),
        "build_meta_sha256": _file_sha256(meta_path),
        "current_worktree_build_sha256": current_worktree_build_sha256,
        "current_worktree_matches_captured_build": (
            current_worktree_build_sha256 == seal.build_sha256
        ),
        "boundary": (
            "The current source bytes exactly match the release-sealed build identity."
            if current_worktree_build_sha256 == seal.build_sha256
            else (
                "The release seal and build-meta retain the build loaded for the terminal "
                "tasks. The current worktree changed after that run; its separately recorded "
                "build hash is not substituted for the captured Companion identity."
            )
        ),
    }


def _lowest_rate(quotes: Sequence[Mapping[str, object]]) -> dict[str, object] | None:
    if not quotes:
        return None
    selected = min(
        quotes,
        key=lambda item: (Decimal(str(item["amount"])), str(item["evidence_sha256"])),
    )
    return {
        "amount": selected["amount"],
        "currency": selected["currency"],
        "price_basis": selected["price_basis"],
        "taxes_included": selected["taxes_included"],
        "price_finality": selected["price_finality"],
        "property": selected["property"],
        "evidence_sha256": selected["evidence_sha256"],
    }


def _derive_assessment(
    sources: Sequence[Mapping[str, object]],
    *,
    publication_gate_attempted: bool,
    publication_gate_passed: bool,
) -> dict[str, object]:
    exact_provider_quotes: dict[str, list[Mapping[str, object]]] = {}
    quote_count_by_provider: dict[str, int] = {}
    terminal_state_by_provider: dict[str, str] = {}
    for source in sources:
        provider = str(source["provider"])
        quotes = [
            _mapping(item, "sealed quote")
            for item in _sequence(source.get("quotes", []), "sealed source.quotes")
        ]
        quote_count_by_provider[provider] = len(quotes)
        terminal_state_by_provider[provider] = str(source["state"])
        exact = [
            item
            for item in quotes
            if item.get("taxes_included") is True
            and item.get("price_finality") == "final_for_rate"
            and item.get("price_basis") in {"per_night", "total_stay"}
            and isinstance(item.get("property"), Mapping)
        ]
        if exact:
            exact_provider_quotes[provider] = exact
    exact_providers = sorted(exact_provider_quotes)
    return {
        "quote_count_by_provider": dict(sorted(quote_count_by_provider.items())),
        "terminal_state_by_provider": dict(sorted(terminal_state_by_provider.items())),
        "exact_all_in_lodging_providers": exact_providers,
        "exact_all_in_lodging_provider_count": len(exact_providers),
        "lowest_exact_all_in_rate_by_provider": {
            provider: _lowest_rate(exact_provider_quotes[provider])
            for provider in exact_providers
        },
        "strict_lodging_provider_threshold": 2,
        "strict_lodging_gate_passed": len(exact_providers) >= 2,
        "publication_gate_attempted": publication_gate_attempted,
        "publication_gate_passed": publication_gate_passed,
    }


def _summary_scope_decisions(summary: Mapping[str, Any]) -> list[dict[str, object]]:
    decisions: list[dict[str, object]] = []
    for item in _sequence(summary.get("sources", []), "source summary.sources"):
        source = _mapping(item, "source summary source")
        if "task_id" in source:
            continue
        decisions.append(
            {
                "provider": _string(source.get("provider"), "scope provider", maximum=32),
                "vertical": _string(source.get("vertical"), "scope vertical", maximum=32),
                "state": _string(source.get("state"), "scope state", maximum=64),
                "coverage_credit": _boolean(
                    source.get("coverage_credit"), "scope coverage_credit"
                ),
            }
        )
    decisions.sort(key=lambda item: (str(item["provider"]), str(item["vertical"])))
    return decisions


def _normalize_scope_decisions(
    raw: Sequence[Mapping[str, object]],
) -> list[dict[str, object]]:
    decisions: list[dict[str, object]] = []
    seen: set[tuple[str, str]] = set()
    for index, item in enumerate(raw):
        provider = _string(item.get("provider"), f"scope_decisions[{index}].provider")
        vertical = _string(item.get("vertical"), f"scope_decisions[{index}].vertical")
        state = _string(item.get("state"), f"scope_decisions[{index}].state")
        coverage_credit = _boolean(
            item.get("coverage_credit"), f"scope_decisions[{index}].coverage_credit"
        )
        if provider not in _PROVIDER_DOMAINS:
            raise EvidenceCaptureError("scope decision provider is outside the allowlist")
        if vertical != "lodging" or state != "skipped_by_user" or coverage_credit is not False:
            raise EvidenceCaptureError(
                "focused scope decisions may only record skipped lodging with no coverage"
            )
        key = (provider, vertical)
        if key in seen:
            raise EvidenceCaptureError("focused scope decisions must be unique")
        seen.add(key)
        decisions.append(
            {
                "provider": provider,
                "vertical": vertical,
                "state": state,
                "coverage_credit": coverage_credit,
            }
        )
    decisions.sort(key=lambda item: (str(item["provider"]), str(item["vertical"])))
    return decisions


def _validate_source_summary(
    summary: Mapping[str, Any],
    sources: Sequence[Mapping[str, object]],
    query: Mapping[str, object],
    companion: Mapping[str, object],
    runtime: Mapping[str, object],
    assessment: Mapping[str, object],
) -> None:
    if summary.get("schema_version") != "tripchord-live-browser-focused-evidence-v1":
        raise EvidenceCaptureError("source summary has an unexpected schema version")
    summary_query = dict(_mapping(summary.get("query"), "source summary.query"))
    expected_summary_query = {
        key: value for key, value in query.items() if key != "recent_quote_reuse_allowed"
    }
    if summary_query != expected_summary_query:
        raise EvidenceCaptureError("source summary query does not match terminal tasks")
    summary_sources = {
        str(item.get("task_id")): item
        for raw in _sequence(summary.get("sources", []), "source summary.sources")
        if (item := _mapping(raw, "source summary source")).get("task_id") is not None
    }
    for source in sources:
        task_id = str(source["task_id"])
        old = _mapping(summary_sources.get(task_id), f"source summary[{task_id}]")
        for field in ("provider", "state", "attempt_count", "quote_count"):
            if old.get(field) != source.get(field):
                raise EvidenceCaptureError(f"source summary {task_id}.{field} is inconsistent")
        if source["quote_count"]:
            quotes = [
                _mapping(item, "sealed quote")
                for item in _sequence(source["quotes"], "sealed quotes")
            ]
            lowest = _lowest_rate(quotes)
            old_lowest = _mapping(old.get("lowest_audited_rate"), "source summary lowest rate")
            if lowest is None:
                raise EvidenceCaptureError("source summary expected a lowest quote")
            old_property = {
                "id": old_lowest.get("property_id"),
                "name": old_lowest.get("property_name"),
            }
            for field in (
                "amount",
                "currency",
                "price_basis",
                "taxes_included",
                "evidence_sha256",
            ):
                if old_lowest.get(field) != lowest.get(field):
                    raise EvidenceCaptureError(
                        f"source summary lowest rate {field} is inconsistent"
                    )
            if old_property != lowest["property"]:
                raise EvidenceCaptureError("source summary lowest property is inconsistent")
    summary_runtime = _mapping(summary.get("runtime"), "source summary.runtime")
    build_identity = _mapping(companion["build_identity"], "companion build identity")
    expected_runtime = {
        "model_provider": runtime["model_provider"],
        "primary_model": runtime["primary_model"],
        "model_required": runtime["model_required"],
        "companion_manifest_version": build_identity["manifest_version"],
        "companion_content_runtime_version": build_identity["content_runtime_version"],
        "companion_build_sha256": build_identity["build_sha256"],
        "companion_runtime_instance_id": companion["runtime_instance_id"],
        "background_reload_verified": True,
        "browser_focused": False,
    }
    if dict(summary_runtime) != expected_runtime:
        raise EvidenceCaptureError("source summary runtime identity is inconsistent")
    old_assessment = _mapping(summary.get("assessment"), "source summary.assessment")
    for field in (
        "strict_lodging_gate_passed",
        "publication_gate_attempted",
        "publication_gate_passed",
    ):
        if old_assessment.get(field) != assessment.get(field):
            raise EvidenceCaptureError(f"source summary assessment.{field} is inconsistent")


def _validate_runtime_binding(
    sources: Sequence[Mapping[str, object]],
    companion: Mapping[str, object],
    runtime: Mapping[str, object],
    release_binding: Mapping[str, object],
) -> None:
    if runtime["model_enabled"] is not True or runtime["model_required"] is not True:
        raise EvidenceCaptureError("focused required-model evidence needs the strict model runtime")
    if (
        runtime["codex_runtime_dependency"] is not False
        or runtime["chatgpt_runtime_dependency"] is not False
    ):
        raise EvidenceCaptureError("runtime dependency boundary is not independent")
    if (
        runtime["browser_companion_auto_reload_enabled"] is not True
        or runtime["browser_companion_supervisor_running"] is not True
    ):
        raise EvidenceCaptureError("Browser Companion background reload runtime is not enabled")
    build_identity = _mapping(companion["build_identity"], "companion.build_identity")
    sealed_identity = _mapping(
        release_binding.get("sealed_identity"), "release binding.sealed_identity"
    )
    if dict(build_identity) != dict(sealed_identity):
        raise EvidenceCaptureError(
            "live Companion identity does not match the retained release receipt"
        )
    source_providers = {str(source["provider"]) for source in sources}
    companion_providers = {
        str(item)
        for item in _sequence(companion["providers"], "companion.providers")
    }
    if not source_providers.issubset(companion_providers):
        raise EvidenceCaptureError("live Companion provider capabilities do not cover the tasks")
    receipt = _mapping(
        runtime["browser_companion_last_reconcile"], "runtime.last_reconcile"
    )
    if receipt.get("state") != "applied":
        raise EvidenceCaptureError("focused evidence requires the applied reload receipt")
    if (
        receipt.get("companion_id") != companion["companion_id"]
        or receipt.get("target_build_sha256") != build_identity["build_sha256"]
        or receipt.get("new_runtime_instance_id") != companion["runtime_instance_id"]
    ):
        raise EvidenceCaptureError("reload receipt does not bind the current Companion runtime")


def _assert_public_safe(value: object, *, path: str = "artifact") -> None:
    if isinstance(value, Mapping):
        for key, item in value.items():
            normalized_key = str(key).lower()
            if any(forbidden in normalized_key for forbidden in _FORBIDDEN_OUTPUT_KEYS):
                raise EvidenceCaptureError(f"sealed output contains forbidden field {path}.{key}")
            _assert_public_safe(item, path=f"{path}.{key}")
        return
    if isinstance(value, list | tuple):
        for index, item in enumerate(value):
            _assert_public_safe(item, path=f"{path}[{index}]")
        return
    if isinstance(value, str):
        if re.search(r"\bsk-[A-Za-z0-9_-]{16,}\b", value):
            raise EvidenceCaptureError(f"sealed output contains an API-key-shaped value at {path}")
        maximum = 4096 if path.endswith("page_url") else 1024
        if len(value) > maximum:
            raise EvidenceCaptureError(f"sealed output contains an overlong string at {path}")


def _input_payload(artifact: Mapping[str, Any]) -> dict[str, object]:
    return {
        "query": artifact["query"],
        "runtime": artifact["runtime"],
        "companion": artifact["companion"],
        "release_binding": artifact["release_binding"],
        "source_tasks": artifact["source_tasks"],
        "scope_decisions": artifact["scope_decisions"],
        "source_artifacts": artifact["source_artifacts"],
    }


def _normalize_source_artifacts(
    raw: Sequence[Mapping[str, str]],
) -> list[dict[str, str]]:
    normalized: list[dict[str, str]] = []
    seen: set[str] = set()
    for index, item in enumerate(raw):
        path = _string(item.get("path"), f"source_artifacts[{index}].path", maximum=512)
        candidate = Path(path)
        if candidate.is_absolute() or ".." in candidate.parts or path in seen:
            raise EvidenceCaptureError("source artifact paths must be unique repository paths")
        seen.add(path)
        normalized.append(
            {
                "path": path,
                "sha256": _digest(
                    item.get("sha256"), f"source_artifacts[{index}].sha256"
                ),
            }
        )
    if not normalized:
        raise EvidenceCaptureError("sealed evidence requires source artifact hashes")
    normalized.sort(key=lambda item: item["path"])
    return normalized


def _claim_boundary(
    companion: Mapping[str, object],
    assessment: Mapping[str, object],
) -> str:
    identity = _mapping(companion["build_identity"], "companion.build_identity")
    provider_count = _integer(
        assessment["exact_all_in_lodging_provider_count"],
        "assessment.exact_all_in_lodging_provider_count",
    )
    return (
        "This sealed artifact makes the focused read-only Browser Companion canary "
        "recomputable from retained terminal task projections on Companion "
        f"{identity['manifest_version']} ({identity['content_runtime_version']}). It proves "
        f"{provider_count} exact all-in lodging provider(s) for this query and retains any "
        "typed provider failure evidence. It is not an accepted itinerary, full three-date "
        "run, universal lowest-price claim, or Publication Gate pass."
    )


def build_sealed_evidence(
    *,
    task_payloads: Sequence[Mapping[str, Any]],
    task_ids: Sequence[str],
    companion_payload: Mapping[str, Any],
    companion_id: str | None,
    runtime_payload: Mapping[str, Any],
    source_summary: Mapping[str, Any] | None,
    source_artifacts: Sequence[Mapping[str, str]],
    release_binding: Mapping[str, object],
    scope_decisions: Sequence[Mapping[str, object]] = (),
) -> dict[str, object]:
    if len(task_payloads) != len(task_ids) or len(task_ids) < 2:
        raise EvidenceCaptureError("focused evidence requires at least two exact task IDs")
    if len(set(task_ids)) != len(task_ids):
        raise EvidenceCaptureError("focused evidence task IDs must be unique")
    sources = [
        _normalize_task(payload, task_id)
        for payload, task_id in zip(task_payloads, task_ids, strict=True)
    ]
    sources.sort(key=lambda item: (str(item["provider"]), str(item["task_id"])))
    query = _mapping(sources[0]["query"], "source query")
    if any(source["query"] != query for source in sources[1:]):
        raise EvidenceCaptureError("focused source tasks do not share one exact query")
    companion = _normalize_companion(companion_payload, companion_id)
    runtime = _normalize_runtime(runtime_payload)
    _validate_runtime_binding(sources, companion, runtime, release_binding)
    source_summary_assessment = (
        _mapping(source_summary.get("assessment"), "source summary.assessment")
        if source_summary is not None
        else {}
    )
    assessment = _derive_assessment(
        sources,
        publication_gate_attempted=(
            _boolean(
                source_summary_assessment.get("publication_gate_attempted"),
                "source summary assessment.publication_gate_attempted",
            )
            if source_summary is not None
            else False
        ),
        publication_gate_passed=(
            _boolean(
                source_summary_assessment.get("publication_gate_passed"),
                "source summary assessment.publication_gate_passed",
            )
            if source_summary is not None
            else False
        ),
    )
    normalized_source_artifacts = _normalize_source_artifacts(source_artifacts)
    summary_scope_decisions = (
        _summary_scope_decisions(source_summary) if source_summary is not None else []
    )
    normalized_scope_decisions = _normalize_scope_decisions(
        [*summary_scope_decisions, *scope_decisions]
    )
    if source_summary is not None:
        _validate_source_summary(source_summary, sources, query, companion, runtime, assessment)
    artifact: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "evidence_closed_at": max(str(source["updated_at"]) for source in sources),
        "scope": "background_read_only_lodging_canary",
        "collection_contract": {
            "http_methods": ["GET"],
            "new_browser_tasks_submitted": False,
            "browser_interaction_performed": False,
            "model_calls_performed": False,
            "raw_page_text_persisted": False,
            "credentials_persisted": False,
            "url_policy": (
                "provider HTTPS URL with semantic query allowlist; tracking values removed"
            ),
        },
        "query": dict(query),
        "runtime": runtime,
        "companion": companion,
        "release_binding": dict(release_binding),
        "source_tasks": sources,
        "scope_decisions": normalized_scope_decisions,
        "derived_assessment": assessment,
        "source_artifacts": normalized_source_artifacts,
        "claim_boundary": _claim_boundary(companion, assessment),
        "integrity": {
            "canonicalization": CANONICALIZATION,
            "task_snapshot_sha256": {
                str(source["task_id"]): _canonical_sha256(source) for source in sources
            },
            "companion_snapshot_sha256": _canonical_sha256(companion),
            "runtime_snapshot_sha256": _canonical_sha256(runtime),
        },
    }
    integrity_payload = dict(_mapping(artifact["integrity"], "artifact.integrity"))
    integrity_payload["input_sha256"] = _canonical_sha256(_input_payload(artifact))
    artifact["integrity"] = integrity_payload
    unsigned = copy.deepcopy(artifact)
    integrity_payload["result_sha256"] = _canonical_sha256(unsigned)
    _assert_public_safe(artifact)
    verify_sealed_evidence(artifact)
    return artifact


def verify_sealed_evidence(raw: object) -> None:
    artifact = _mapping(raw, "sealed artifact")
    if artifact.get("schema_version") != SCHEMA_VERSION:
        raise EvidenceCaptureError("sealed artifact has an unexpected schema version")
    integrity = _mapping(artifact.get("integrity"), "sealed artifact.integrity")
    if integrity.get("canonicalization") != CANONICALIZATION:
        raise EvidenceCaptureError("sealed artifact canonicalization is unsupported")
    source_tasks = [
        _mapping(item, "sealed source task")
        for item in _sequence(artifact.get("source_tasks"), "sealed source tasks")
    ]
    task_hashes = _mapping(
        integrity.get("task_snapshot_sha256"), "integrity.task_snapshot_sha256"
    )
    expected_task_hashes = {
        str(source["task_id"]): _canonical_sha256(source) for source in source_tasks
    }
    if dict(task_hashes) != expected_task_hashes:
        raise EvidenceCaptureError("sealed task snapshot digest mismatch")
    if integrity.get("companion_snapshot_sha256") != _canonical_sha256(
        artifact.get("companion")
    ):
        raise EvidenceCaptureError("sealed Companion snapshot digest mismatch")
    if integrity.get("runtime_snapshot_sha256") != _canonical_sha256(artifact.get("runtime")):
        raise EvidenceCaptureError("sealed runtime snapshot digest mismatch")
    if integrity.get("input_sha256") != _canonical_sha256(_input_payload(artifact)):
        raise EvidenceCaptureError("sealed input digest mismatch")
    old_assessment = _mapping(
        artifact.get("derived_assessment"), "sealed artifact.derived_assessment"
    )
    recomputed = _derive_assessment(
        source_tasks,
        publication_gate_attempted=_boolean(
            old_assessment.get("publication_gate_attempted"),
            "derived assessment.publication_gate_attempted",
        ),
        publication_gate_passed=_boolean(
            old_assessment.get("publication_gate_passed"),
            "derived assessment.publication_gate_passed",
        ),
    )
    if dict(old_assessment) != recomputed:
        raise EvidenceCaptureError("sealed derived assessment is not reproducible")
    unsigned = copy.deepcopy(dict(artifact))
    unsigned_integrity = dict(_mapping(unsigned.get("integrity"), "sealed integrity"))
    result_sha256 = unsigned_integrity.pop("result_sha256", None)
    unsigned["integrity"] = unsigned_integrity
    if result_sha256 != _canonical_sha256(unsigned):
        raise EvidenceCaptureError("sealed result digest mismatch")
    _assert_public_safe(artifact)


def _fsync_directory(directory: Path) -> None:
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
    descriptor = os.open(directory, flags)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def build_run_summary(
    raw: object,
    *,
    sealed_artifact_name: str,
) -> dict[str, object]:
    verify_sealed_evidence(raw)
    artifact = _mapping(raw, "sealed artifact")
    runtime = _mapping(artifact["runtime"], "sealed runtime")
    companion = _mapping(artifact["companion"], "sealed companion")
    identity = _mapping(companion["build_identity"], "sealed build identity")
    assessment = _mapping(artifact["derived_assessment"], "sealed assessment")
    lowest_by_provider = _mapping(
        assessment["lowest_exact_all_in_rate_by_provider"],
        "sealed lowest rates",
    )
    sources: list[dict[str, object]] = []
    for raw_source in _sequence(artifact["source_tasks"], "sealed source tasks"):
        source = _mapping(raw_source, "sealed source task")
        item: dict[str, object] = {
            "task_id": source["task_id"],
            "provider": source["provider"],
            "state": source["state"],
            "attempt_count": source["attempt_count"],
            "quote_count": source["quote_count"],
        }
        lowest = lowest_by_provider.get(str(source["provider"]))
        if lowest is not None:
            lowest_rate = _mapping(lowest, "sealed lowest provider rate")
            property_identity = _mapping(
                lowest_rate["property"], "sealed lowest property"
            )
            item["lowest_audited_rate"] = {
                "amount": lowest_rate["amount"],
                "currency": lowest_rate["currency"],
                "price_basis": lowest_rate["price_basis"],
                "taxes_included": lowest_rate["taxes_included"],
                "price_finality": lowest_rate["price_finality"],
                "property_id": property_identity["id"],
                "property_name": property_identity["name"],
                "evidence_sha256": lowest_rate["evidence_sha256"],
            }
        failure_raw = source.get("failure")
        if failure_raw is not None:
            failure = _mapping(failure_raw, "sealed failure")
            failure_summary: dict[str, object] = {
                "code": failure["code"],
                "retryable": failure["retryable"],
            }
            navigation_raw = failure.get("navigation_diagnostic")
            if navigation_raw is not None:
                navigation = _mapping(navigation_raw, "sealed navigation")
                rejected = _mapping(navigation["rejected_url"], "sealed rejected URL")
                returned = _mapping(
                    navigation["login_return_url"], "sealed login return URL"
                )
                failure_summary.update(
                    {
                        "reason": navigation["reason"],
                        "redirect_host": rejected["host"],
                        "redirect_path_shape": rejected["path_shape"],
                        "login_return_host": returned["host"],
                        "login_return_path_shape": returned["path_shape"],
                    }
                )
            item["failure"] = failure_summary
        sources.append(item)
    integrity = _mapping(artifact["integrity"], "sealed integrity")
    release_binding = _mapping(artifact["release_binding"], "sealed release binding")
    provider_count = _integer(
        assessment["exact_all_in_lodging_provider_count"],
        "sealed assessment.exact_all_in_lodging_provider_count",
    )
    summary: dict[str, object] = {
        "schema_version": "tripchord-live-browser-focused-run-summary-v2",
        "captured_at": artifact["evidence_closed_at"],
        "scope": artifact["scope"],
        "query": artifact["query"],
        "runtime": {
            "model_provider": runtime["model_provider"],
            "primary_model": runtime["primary_model"],
            "model_required": runtime["model_required"],
            "companion_manifest_version": identity["manifest_version"],
            "companion_content_runtime_version": identity["content_runtime_version"],
            "companion_build_sha256": identity["build_sha256"],
            "companion_runtime_instance_id": companion["runtime_instance_id"],
            "background_reload_verified": True,
            "browser_focused": False,
            "current_worktree_matches_captured_build": release_binding[
                "current_worktree_matches_captured_build"
            ],
        },
        "sources": sources,
        "scope_decisions": artifact["scope_decisions"],
        "assessment": {
            "exact_all_in_lodging_provider_count": provider_count,
            "one_provider_exact_lodging_quote": provider_count == 1,
            "two_provider_exact_lodging_quote": provider_count >= 2,
            "strict_lodging_gate_passed": assessment["strict_lodging_gate_passed"],
            "publication_gate_attempted": assessment["publication_gate_attempted"],
            "publication_gate_passed": assessment["publication_gate_passed"],
        },
        "sealed_evidence": {
            "path": sealed_artifact_name,
            "input_sha256": integrity["input_sha256"],
            "result_sha256": integrity["result_sha256"],
            "source_artifact_count": len(
                _sequence(artifact["source_artifacts"], "sealed source artifacts")
            ),
        },
        "claim_boundary": artifact["claim_boundary"],
    }
    summary["result_sha256"] = _canonical_sha256(summary)
    _assert_public_safe(summary)
    return summary


def _atomic_write_json(
    path: Path,
    payload: Mapping[str, object],
    *,
    mode: int = 0o600,
) -> None:
    if mode not in {0o600, 0o644}:
        raise EvidenceCaptureError("evidence output mode is outside the fixed allowlist")
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() or path.is_symlink():
        raise EvidenceCaptureError("refusing to overwrite an existing evidence artifact")
    temporary = path.parent / f".{path.name}.tmp-{os.getpid()}-{secrets.token_hex(8)}"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = os.open(temporary, flags, mode)
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = -1
            stream.write(json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8"))
            stream.write(b"\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.link(temporary, path, follow_symlinks=False)
        temporary.unlink()
        _fsync_directory(path.parent)
    except FileExistsError as exc:
        raise EvidenceCaptureError("refusing to overwrite an existing evidence artifact") from exc
    except OSError as exc:
        raise EvidenceCaptureError(f"cannot atomically write evidence artifact: {path}") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise EvidenceCaptureError(f"cannot read {label}: {path}") from exc
    if not isinstance(payload, dict):
        raise EvidenceCaptureError(f"{label} must be a JSON object")
    return payload


def capture_from_runtime(
    *,
    repository: Path,
    base_url: str,
    bridge_token_file: Path,
    task_ids: Sequence[str],
    companion_id: str | None,
    source_summary_path: Path | None,
    skipped_lodging_providers: Sequence[str] = (),
) -> dict[str, object]:
    base = _validate_base_url(base_url)
    token = _secure_token(bridge_token_file)
    if len(task_ids) < 2 or any(not _TASK_ID.fullmatch(task_id) for task_id in task_ids):
        raise EvidenceCaptureError("at least two valid --task-id values are required")
    with httpx.Client(
        base_url=base,
        follow_redirects=False,
        timeout=10.0,
        trust_env=False,
    ) as client:
        task_payloads = [
            _fetch_json(
                client,
                f"/browser-bridge/v1/tasks/{quote(task_id, safe='')}",
                bridge_token=token,
            )
            for task_id in task_ids
        ]
        companion_payload = _fetch_json(
            client,
            "/browser-bridge/v1/companions/status",
            bridge_token=token,
        )
        runtime_payload = _fetch_json(client, "/api/v1/agents/runtime")
    source_summary = (
        _load_json(source_summary_path, "source summary")
        if source_summary_path is not None
        else None
    )
    release_binding = _release_binding(repository)
    source_artifacts = _source_artifact_receipts(repository, source_summary_path)
    if _release_binding(repository) != release_binding:
        raise EvidenceCaptureError("Companion source changed during evidence capture")
    if _source_artifact_receipts(repository, source_summary_path) != source_artifacts:
        raise EvidenceCaptureError("source artifacts changed during evidence capture")
    if (
        source_summary_path is not None
        and _load_json(source_summary_path, "source summary") != source_summary
    ):
        raise EvidenceCaptureError("source summary changed during evidence capture")
    return build_sealed_evidence(
        task_payloads=task_payloads,
        task_ids=task_ids,
        companion_payload=companion_payload,
        companion_id=companion_id,
        runtime_payload=runtime_payload,
        source_summary=source_summary,
        source_artifacts=source_artifacts,
        release_binding=release_binding,
        scope_decisions=[
            {
                "provider": provider,
                "vertical": "lodging",
                "state": "skipped_by_user",
                "coverage_credit": False,
            }
            for provider in skipped_lodging_providers
        ],
    )


def main() -> int:
    args = _arguments()
    try:
        repository = args.repository.resolve()
        if args.verify is not None:
            verify_stat = args.verify.lstat()
            if (
                stat.S_ISLNK(verify_stat.st_mode)
                or not stat.S_ISREG(verify_stat.st_mode)
                or stat.S_IMODE(verify_stat.st_mode) != 0o600
            ):
                raise EvidenceCaptureError("sealed evidence must be a regular mode-0600 file")
            artifact = _load_json(args.verify, "sealed evidence")
            verify_sealed_evidence(artifact)
            if args.summary_output is not None:
                _atomic_write_json(
                    args.summary_output,
                    build_run_summary(
                        artifact,
                        sealed_artifact_name=args.verify.name,
                    ),
                    mode=0o644,
                )
            print(f"verified {args.verify}")
            return 0
        required = {
            "--bridge-token-file": args.bridge_token_file,
            "--output": args.output,
        }
        missing = [name for name, value in required.items() if value is None]
        if missing:
            raise EvidenceCaptureError(f"capture mode requires: {', '.join(missing)}")
        artifact = capture_from_runtime(
            repository=repository,
            base_url=args.base_url,
            bridge_token_file=args.bridge_token_file,
            task_ids=args.task_id,
            companion_id=args.companion_id,
            source_summary_path=args.source_summary,
            skipped_lodging_providers=args.skipped_lodging_provider,
        )
        _atomic_write_json(args.output, artifact)
        verify_sealed_evidence(_load_json(args.output, "sealed evidence"))
        if stat.S_IMODE(args.output.lstat().st_mode) != 0o600:
            raise EvidenceCaptureError("sealed evidence mode is not 0600")
        if args.summary_output is not None:
            _atomic_write_json(
                args.summary_output,
                build_run_summary(
                    artifact,
                    sealed_artifact_name=args.output.name,
                ),
                mode=0o644,
            )
        print(f"sealed {args.output}")
        return 0
    except EvidenceCaptureError as exc:
        print(f"evidence capture failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
